### ISSUE TITLE
Can't create a new tab in my browser

### ISSUE THREAD

**Issue by Berseck20** [cobrateam/splinter#1008]
hello, I am starting to use this framework and I want to start a browser, go to a url and then create a new tab.

when i try to do that i get the following error:

Traceback (most recent call last):
  File "d:\Usuario\Desktop\BotCreadosPorMi\testeodecosas.py", line 21, in <module>
    browserReddit.new_tab("https://smailpro.com")
  File "D:\python3910\lib\site-packages\splinter\driver\__init__.py", line 68, in new_tab
    raise NotImplementedError("%s doesn't open a new tab." % self.driver_name)
NotImplementedError: Firefox doesn't open a new tab.

**Comment by jsfehler** [comment]
@Berseck20 A well formed issue should include the following:

- A reproducible example, formatted such that github displays it as a code block and preserves indentation.
- A full traceback

In this particular case, the answer is: You used `Firefox` as the name of the browser. The correct name is 'firefox'.
