### ISSUE TITLE
(selenium) UserWarning: find_elements_by_css_selector is deprecated

### ISSUE THREAD

**Issue by walksonair** [cobrateam/splinter#1036]
Hello, didn't see an open issue on this so letting devs know about 

`/usr/local/lib/python3.9/site-packages/selenium/webdriver/remote/webelement.py:502: UserWarning: find_elements_by_css_selector is deprecated. Please use find_elements(by=By.CSS_SELECTOR, value=css_selector) instead
  warnings.warn("find_elements_by_css_selector is deprecated. Please use find_elements(by=By.CSS_SELECTOR, value=css_selector) instead")`

splinter==0.17.0
selenium==4.1.3

**Comment by jsfehler** [comment]
This has been fixed on the master branch.
