### ISSUE TITLE
Release version 0.18.0 to pypi

### ISSUE THREAD

**Issue by jsfehler** [cobrateam/splinter#1047]
Release is tagged, just needs to be built and uploaded to pypi.

**Comment by fsouza** [comment]
I can take care of that later today.

@andrewsmedina @jsfehler any objections to automating this? Like, whenever we tag the repo, we'd run the command to upload it to pypi?

**Comment by fsouza** [comment]
Done: https://pypi.org/project/splinter/0.18.0/

We can track automation elsewhere.
