### ISSUE TITLE
Logging setup in browser.py clobbers other logging

### ISSUE THREAD

**Issue by jordanvance** [cobrateam/splinter#1051]
The logging in browser.py calls the root logger, which can cause unexpected changes to the setup and output in some testing environments. It would be preferable to have it log to something like:

```
LOG = logging.getLogger(__name__)
...
except ImportError as e:
    LOG.debug(f"Import warning: {e}")
```

**Comment by jsfehler** [comment]
@jordanvance Good catch. Yes, not getting a logger just for splinter is a mistake.

@agroszer The reason this logging is set to the debug level is that it's only useful for debugging the splinter library. 99% of the time it's not useful information. The correct behaviour is to ignore missing but optional imports, so the log message would just be noise. When testing if splinter is working at all, however, this message can solve an extremely simple gotcha: You forgot a dependency. If all else fails, you can setup your logger before importing splinter and get something meaningful.

**Comment by fsouza** [comment]
Closed via #1054.

**Comment by agroszer** [comment]
can we get a release please?

**Comment by fsouza** [comment]
Sorry completely missed this. @jsfehler should we push out a bugfix-release? Or should we wait for the next regular release?

**Comment by fsouza** [comment]
Sounds good I'll publish 0.18.1
