### ISSUE TITLE
attach_file work with flask?

### ISSUE THREAD

**Issue by marcuxyz** [cobrateam/splinter#1080]
Hi,
I have a question.

`browser.attach_file` work with flask?
I've been trying to work with this for almost 1 month. :(

an error always happens when the redirect is done:
`ValueError: read of closed file `

Maybe... if do test with `return redirect` instead `return "|".join(buffer) `, this break:

https://github.com/cobrateam/splinter/blob/bd7b82161802f07a7f79e6b1e74557f4cf23d029/tests/fake_webapp.py#L117

I change the code to:

```python
@app.route("/upload", methods=["GET", "POST"])
def upload_file():
    if request.method == "POST":
        f = request.files["file"]
        return redirect('/')
```

and run the test, with the follow command:

```shell
tox -e tests -- tests/test_flaskclient.py
```

<img width="1714" alt="Screen Shot 2022-08-05 at 11 12 45" src="https://user-images.githubusercontent.com/9499562/183095325-a785096b-1427-4bdb-b18d-396a8b72e847.png">

Thanks

**Comment by jsfehler** [comment]
@marcuxyz Can you provide the command you're using to run the tests, a full traceback, plus the operating system and python version you're using?

**Comment by marcuxyz** [comment]
@jsfehler I'm use python 3.10 and Mac OS Monterey.  `pytest` is the command used to run tests.
