### ISSUE TITLE
Browser raise NoneType

### ISSUE THREAD

**Issue by MacroHongZ** [cobrateam/splinter#1089]
Code:
'''
from splinter import Browser

browser = Browser('chrome')
'''

result:
TypeError: 'NoneType' object is not callable

I can't find the reason

**Comment by fsouza** [comment]
@MacroHongZ do you have a stack trace?

**Comment by andrewsmedina** [comment]
@jsfehler what do you think about to create an issue to improve this error message to users know that is necessary to install selenium?

**Comment by adamcheasley** [comment]
@jsfehler thanks for confirming! Yes, +1 for a better error message there.

**Comment by jsfehler** [comment]
@andrewsmedina In the future we can check the driver name and return a more specific message. I've also updated the docs to make the installation process more obvious to new users.

**Comment by MacroHongZ** [comment]
@jsfehler 
Thanks for your comment, the error is indeed due to Selenium not installed, but the error message is too ambiguous to find the cause. I would suggest that the doc could be updated to ：
“ pip install selenium
pip install splinter“
