### ISSUE TITLE
clicking links with firefox driver doesn't reset HTTP statuscode

### ISSUE THREAD

**Issue by muelli** [cobrateam/splinter#109]
I click_link_by_text() and the link in question returns 404. Splinter, however, doesn't expose that that new statuscode.

**Comment by peterlauri** [comment]
This is an very old issue, but we are facing these problems. We cannot clearly detect an regression with 500 result in clicking an element. I wouldn't mind doing these changes, if someone of the core devs could have a short chat/talk with me related what the scope of doing this would mean.

I've been looking a bit in the code, and all the click_link* stuff, are just **find the element and do a .first.click()** on the that element. So the implementation would reside inside of the Element.click() I guess.

I guess this would be treated as an opt-in feature, as doing this change would probably break many projects test suites.

**Comment by andrewsmedina** [comment]
after the https://github.com/cobrateam/splinter/commit/2e5135460610149a1082b2aaca61fffc10beae40 in `0.8` the drivers based on webdriver will `raise NotImplementedError` in `status_code`
