### ISSUE TITLE
Can´t find Iframe

### ISSUE THREAD

**Issue by Peliikan** [cobrateam/splinter#1098]
So I am trying to find an Iframe with splinter and I can find the first one with,

with browser.get_iframe('iframemodal') as iframe:
    iframe.do_stuff()

and instead of iframemodal I use index which is 0 and this works fine but when I press the box in that Iframe it opens another Iframe without a name or id and everytime the index order of that newly opened iframe changes so I cant use index again it has a title but I think get.iframe doesnt work with css is there a way to find the second iframe ?

**Comment by riddhikt** [comment]
Hi,
Instead of using name or id try using xpath, something like this: 
` with browser.get_iframe(browser.find_by_xpath('//*[@class="ABC"]').first) as iframe:`
