### ISSUE TITLE
Do not focus on browser window (when using Selenium) on GNU/Linux

### ISSUE THREAD

**Issue by turicas** [cobrateam/splinter#110]
I'm running Ubuntu 11.04 and when I use some browser provided Selenium (firefox or chrome) it puts the focus on browser window when running the tests.

It's **annoying** because I can't use the computer when the tests are runnig! (WTF?)

One solution is to run the browser window in another X DISPLAY, but this is not the perfect solution since I can't see the browser window if some test fail (so I can't debug it).

**Comment by turicas** [comment]
@SEJeff, thanks for the feedback! :+1: I didn't know [PyVirtualDisplay](https://pypi.python.org/pypi/PyVirtualDisplay).

**Comment by SEJeff** [comment]
Glad to give you a real solution to your issue :)
