### ISSUE TITLE
Changelog: Single file?

### ISSUE THREAD

**Issue by tony** [cobrateam/splinter#1114]
I think it's far easier to comprehend across multiple versions when release notes are just text, in a single file - without extra distractions / spacing / etc.   Is it possible to just to have a single changelog file?

Example: https://github.com/SeleniumHQ/selenium/blob/selenium-4.7.2-python/py/CHANGES

**Comment by jsfehler** [comment]
I don't mind the idea of a single file changelog in the format of https://keepachangelog.com/en/1.0.0/.

The last few releases have a format that's compatible, but only changelogs need to be rewritten.

**Comment by harshit-wadhwani** [comment]
Hey @jsfehler @tony can I work on this issue ?, is it still active ? since 9 months have been passed.
