### ISSUE TITLE
Config cannot be imported

### ISSUE THREAD

**Issue by ctasca** [cobrateam/splinter#1151]
I have just installed today splinter via pip at the latest version and the config.py is missing from it as well as from __init__.py

if I do "from splinter import Browser, Config" ...Config is not found

from splinter import Browser, Config
ImportError: cannot import name 'Config' from 'splinter' (/Library/Python/3.9/lib/python/site-packages/splinter/__init__.py)

**Comment by fsouza** [comment]
You should import config from `splinter.config`. Curious on why you expect it to be available in `splinter`. Are you following any docs? If so, we should fix it.

**Comment by ctasca** [comment]
The config.py was completely missing from the package when installed via pip. I had to clone the repo in site-packages and solved it this way. I was following the doc at https://splinter.readthedocs.io/en/latest/config.html

**Comment by fsouza** [comment]
Hmm that's because config is only available on master, it hasn't been released yet. I guess the bug is that latest points to master instead of the most recent tag? 🤔

**Comment by ctasca** [comment]
It is surely a nice feature to have Config and being able to set fullscreen mode. Maybe can you suggest how it can be done without using Config on Chrome webdriver? Or at least being able to set the browser window size?

**Comment by jsfehler** [comment]
Closing this issue since the Config object is available in the latest Splinter version.
