### ISSUE TITLE
Parallel script execution

### ISSUE THREAD

**Issue by NikitaMishin** [cobrateam/splinter#1157]
Is it possible to perform async calls to execute JavaScript in parallel? Right now if i have 1 browser instance and i want to execute several async callbacks in browser. They would be executed in a sequential manner rn.
Id like to execute them asynchronously. So is this possible?

**Comment by GuillaumeCisco** [comment]
I think you can use async/await in your script, with some Prmose.all

**Comment by jsfehler** [comment]
Closing, as this isn't a Splinter issue.
