### ISSUE TITLE
selenium.WebDriver no longer accepts desired_capabilities as a kwarg

### ISSUE THREAD

**Issue by miraculixx** [cobrateam/splinter#1213]
***Issue***

The example code given in the [docs](https://splinter.readthedocs.io/en/stable/drivers/remote.html#usage) for passing desired capabilities is no longer working (splinter >= 0.20.0, selenium >= 14.5.2)

``` python
Browser('remote',  browser='Chrome',  command_executor=remote_server_url, 
               desired_capabilities={ ... })         
=>
File ~/.../lib/python3.9/site-packages/splinter/driver/webdriver/setup.py:34, in _setup_chrome(driver_class, config, 
...
TypeError: __init__() got an unexpected keyword argument 'desired_capabilities'
```

***Expected***

Passing the `desired_capabilities` kwarg to WebDriver has been deprecated in Selenium for quite some time. It has been [removed in selenium 14.5.2](https://github.com/SeleniumHQ/selenium/commit/9f5801c82fb3be3d5850707c46c3f8176e3ccd8e). Splinter should either no longer support it, too, or provide a shim by converting the desired_capabilities to respective Options.set_capability() calls.

This works:

```
options = ChromeOptions()
[options.set_capability(c, v) for c, v in caps.items()]
Browser('remote',  browser='Chrome',  command_executor=remote_server_url, 
               options=options) 
```

***Environment***

Python 3.9 / 3.10
Splinter 0.20.0 
Selenium 14.5.2 (installed as `pip install splinter[selenium]`)

**Comment by fsouza** [comment]
Yeah, we need to update the docs. Wanna send a patch?
