### ISSUE TITLE
browser.find_by_css(..) doesn't work with non HTML elements

### ISSUE THREAD

**Issue by osroca** [cobrateam/splinter#139]
I tried to use `find_by_css` over a SVG element and it doesn't return anything. However JQuery script makes the trick

```
browser.find_by_css('svg#my_id > g ') # this doesn't return anything
browser.evaluate_script("$('svg#my_id > g').length") # returns the number of g elements in svg#my_id
```

**Comment by jsfehler** [comment]
Closing, since this isn't a splinter issue or something we can easily patch over.
