### ISSUE TITLE
splinter on python 3

### ISSUE THREAD

**Issue by andrewsmedina** [cobrateam/splinter#165]
For this it is need that lxml, selenium, and zope test browser work in python 3

**Comment by lrowe** [comment]
@fgimian I don't think your Python 3 compatibility update got things quite right. I was using splinter 0.6.0 with webdriver under Python 3 and things worked, but after upgrading to 0.7.1 I am seeing many errors like this:
```
>       assert text in context.browser.title
E       TypeError: Type str doesn't support the buffer API
```

I don't think you should be decoding strings to bytes for the title or html. Instead just leave it as an encoded string:

    @property
    def title(self):
        if sys.version_info[0] > 2:
            return self.driver.title.encode('utf-8')
        else:
            return self.driver.title

https://github.com/cobrateam/splinter/commit/5d14dad0b43a7f396f9a9b2d0601ca27e8d78bfc?diff=unified#diff-57bd95ad52ad7f3fc6217684677d0576R43

If a different driver returns a bytes object then in probably should be decoded to a string.

**Comment by Liang-WenYan** [comment]
Awesome!
