### ISSUE TITLE
access iframe without id tag

### ISSUE THREAD

**Issue by CRP** [cobrateam/splinter#166]
Is there some way to access iframes that have no id tags?
for example the following:

<iframe src="https://www.something.com/script.jsp" height="400" width="500" frameborder="0">
bla bla
</iframe>

Thanks

**Comment by aswwindkk** [comment]
i don't get it ,like this ?
with browser.get_iframe(1) as iframe:

**Comment by kennedto** [comment]
How can I find the methods supported by iframe?
