### ISSUE TITLE
Select method for WebDriverElement

### ISSUE THREAD

**Issue by michelts** [cobrateam/splinter#191]
Hi, I missed the possibility to select a widget after find it by css:

``` python
selects = browser.find_by_css('#my-prefixed-formset select')
for s in selects:
    s.select('some-value')  # won't work
    s.find_by_value('some-value').first._element.click()  # works ok
```

The second line of the forloop uses the same approach of the select from the WebDriver instance. I propose to create the select option for the WebDriverElement too, just like the check, fill and type methods.

This is specially useful for formsets, when I don't want to know each field prefix to fill.

If you agree, I can send a pull request.

**Comment by jsfehler** [comment]
WebDriverElement currently supports the select method, so closing this issue.
