### ISSUE TITLE
idea: open browser window maximized

### ISSUE THREAD

**Issue by jabbalaci** [cobrateam/splinter#197]
Hi,

I would like to open the Chrome browser window in a maximized way, i.e. it should fill the whole screen. As a temporary solution, I patched my `splinter/driver/webdriver/chrome.py` file by adding the following line:

options.add_argument("--start-maximized")

It would be nice to create a browser this way for instance:

options = ["--start-maximized"]
br = Browser('chrome', options=options)

Best,

Laszlo

**Comment by jsfehler** [comment]
Since #494, you can pass options to the Browser instance.
