### ISSUE TITLE
Improve the api docstrings with examples

### ISSUE THREAD

**Issue by andrewsmedina** [cobrateam/splinter#202]

**Comment by kishan3** [comment]
This refers to `splinter/docs/api` ,  right?

**Comment by andrewsmedina** [comment]
Yes

**Comment by jsfehler** [comment]
The documentation currently has a decent number of examples. Due to the age of this issue and lack of specific details, I'm closing it. If there's any specific sections with missing and/or unclear documentation, they can be addressed in separate issues.
