### ISSUE TITLE
Need functionality to check whether page has been loaded

### ISSUE THREAD

**Issue by sidchilling** [cobrateam/splinter#237]
It is a normal requirement that any point of time we should be able to inspect whether the browser has completed loading the page.

This is a requirement because when a page navigation happens via JavaScript, say on the click of a button somewhere, there is no way of knowing whether the browser has completed loading the page as on click the control comes back (as opposed to visit() where control does not come back unless the page has been completely loaded).

With this functionality, one can inspect and then continue when the page has been loaded.

**Comment by marufmax** [comment]
Is this still implemented? I am eagerly waiting for this feature

**Comment by jsfehler** [comment]
Selenium now waits for page load by default. It must be disabled via an Options parameter: https://www.selenium.dev/documentation/webdriver/drivers/options/#pageloadstrategy

It won't handle complex hydration scenarios, but strategies for dealing with that are going to be specific to the web app being automated.
