### ISSUE TITLE
visit() method with Firefox webdriver fails to maintain state

### ISSUE THREAD

**Issue by pgcd** [cobrateam/splinter#244]
It appears the visit() method clears the browser cookies or something - at least using the Firefox webdriver.
My test case was as follow (Django):

```
def test_login_is_working(self):
    self.login()
    self.assertIn(self.basicuser.first_name, self.browser.html)
    self.browser.visit("%s%s" % (self.live_server_url, reverse('sotd_wearing_list_mine')))
    self.assertIn(self.basicuser.first_name, self.browser.html)
```

The last assertion fails - the user is now logged out. Changing the code as follows fixed it:

```
def test_login_is_working(self):
    self.login()
    self.assertIn(self.basicuser.first_name, self.browser.html)
    self.browser.click_link_by_href(reverse('sotd_wearing_list_mine'))
    self.assertIn(self.basicuser.first_name, self.browser.html)
```

So, if I click() the link I remain logged in, while visit()ing the same URL kicks me out.
I realize that this might be by design but, if that is the case, I believe the documentation  for visit() should be updated to reflect this.

**Comment by blueyed** [comment]
@pgcd 
I've seen a similar issue today, but have not debugged it yet.

Do you have any new insights for this issue?

In my case I am trying to inject a cookie from Django's test `client`, which then appears to get lost when `visit`ing the admin page.

**Comment by blueyed** [comment]
This might be caused by https://github.com/cobrateam/splinter/issues/245.

**Comment by andrewsmedina** [comment]
@blueyed I believe that #245 is not related because django driver does not use the request handler.

**Comment by pgcd** [comment]
Sorry, I haven't been back on that project in a while now so I don't have anything to add at the moment, but I'm now on something else that uses Splinter so if I stumble across this again I'll try and get more info.

**Comment by andrewsmedina** [comment]
after the https://github.com/cobrateam/splinter/commit/2e5135460610149a1082b2aaca61fffc10beae40 in `0.8` the drivers based on webdriver will `raise NotImplementedError` in `status_code`
