### ISSUE TITLE
HTTPConnection on _create_connection doesn't send cookies

### ISSUE THREAD

**Issue by gabrielpjordao** [cobrateam/splinter#245]
Hello,

Currently, `_create_connection` https://github.com/cobrateam/splinter/blob/master/splinter/request_handler/request_handler.py#L38 doesn't send cookies with the request. Sometimes, this may cause errors. 

For instance, if we make an attempt to visit a page which demands auth, and the server answers with 403 (Forbidden), since it won't be able to verify the user, `ensure_success_response` will fail and visiting the page will not be possible.

What's the right approach to handle it? add cookies to HTTPConnection?

**Comment by andrewsmedina** [comment]
We don't have the request_handler proxy anymore. So, I'm closing this.
