### ISSUE TITLE
Performance degradation under particular circumstances

### ISSUE THREAD

**Issue by ErinCall** [cobrateam/splinter#247]
Hi, I'm using Splinter to test my web applications locally. I've noticed a performance degradation when repeatedly `visit`ing a url that may respond to requests for static assets with `304 Not Modified`. In particular, calls to `visit` after the second one will take several seconds each.

I've created [a minimal project](https://github.com/AndrewLorente/slow_splinter_demo) that demonstrates the performance problems. The README for that project has my investigations in depth, but to summarize: after the browser fetches a page with a Not Modified static asset, the manual request that Splinter makes in `visit` will be very slow.

In #241, there's discussion of adding a flag to `visit` so that it doesn't manually fetch the url. That would be a reasonable workaround but it seems like better yet would be to fix the underlying issue. Unfortunately I've exhausted my ability to debug this any further. :(

**Comment by andrewsmedina** [comment]
I believe that this issue is related to #241.

**Comment by andrewsmedina** [comment]
after the https://github.com/cobrateam/splinter/commit/2e5135460610149a1082b2aaca61fffc10beae40 in `0.8` the drivers based on webdriver will `raise NotImplementedError` in `status_code`
