### ISSUE TITLE
Support Internet Explorer

### ISSUE THREAD

**Issue by fsouza** [cobrateam/splinter#25]
Add support to Internet Explorer using the webdriver Splinter driver.

**Comment by parkouss** [comment]
Maybe appveyor can help here ? (http://www.appveyor.com/)
This is the windows equivalent for travis-ci, also free for open source projects.
Here is an example of the configuration file:
https://github.com/mozilla/mozregression/blob/master/appveyor.yml

**Comment by kanth240** [comment]
For folks who want to use IE with splinter, check this out: https://stirunagari.wordpress.com/2017/08/20/using-internet-explorer-web-driver-with-splinter-framework/

**Comment by ckolumbus** [comment]
just added a comment to the blog entry that @kanth240 mentioned above. with a minor tweak the solution there works perfectly for my scenario.
What is the issue that prevents us from integration this into splinter? Test env?

**Comment by jsfehler** [comment]
Closing this issue. Internet Explorer is very, very dead at this point. Microsoft hasn't supported it in years. Splinter supports Edge but that's as far as we can go.
