### ISSUE TITLE
fill_form() doesn't work with <input type="tel"> - but fill() does

### ISSUE THREAD

**Issue by victorhooi** [cobrateam/splinter#275]
Hi,

I have a input element like this:

```
<input type="tel" name="number" class="cc_number" placeholder="Credit card number" autocomplete="off" maxlength="16" id="number">
```

I'm calling fill_form on it, and passing a dict like:

```
cc_details = {
    'number': '23424234234234234',
    'name': 'Joe blogs',
    ...
}
```

All other fields (e.g. with `type="text"`) get set correctly, however the `type="tel"` field does not.

However, calling `.fill('number', '23424234234234234')` **does** work.

Is there some way of adding `type="tel"` support into `fill_form` as well?

Cheers,
Victor

**Comment by andrewsmedina** [comment]
This is working in the latest version
