### ISSUE TITLE
Use proxy with PhantomJS?

### ISSUE THREAD

**Issue by Bazza74** [cobrateam/splinter#279]
Hi, I can use a proxy with firefox using: 

profile = {'network.proxy.http': 'IPADDRESSS',
'network.proxy.http_port': 21301,
'network.proxy.type': 1}

and setting that on the browser instance, but when I switch to PhantomJS it doesn't work.

Do I have to do it differently with PhantomJS? Or is it just not possible?

Thanks for your help in advance!

**Comment by andrewsmedina** [comment]
I believe that this isssue is related to #241. So removing the "request handler" should fix the access using proxy.

**Comment by andrewsmedina** [comment]
With chrome and firefox headless the phantom will be removed from splinter
