### ISSUE TITLE
is_element_not_present_by_* are slow

### ISSUE THREAD

**Issue by kedder** [cobrateam/splinter#293]
`is_element_not_present_by_*` set of functions are waiting for timeout regardless whether element is present or not. There is a waiting loop in `BaseWebDriver.is_element_not_present()` that is waiting for negative condition and later in `BaseWebDriver.find_by()` down in traceback that is waiting for positive condition.

This creates hudnreds of requests to webdriver during wait for condition that is actually satisfied immediately.

**Comment by wurenbuxiao** [comment]
I am facing this question, too. But i use the function in selenium instead to solve this question, like use the find_element_by_xxx in the try/except. it is really fast.

**Comment by jsfehler** [comment]
@andrewsmedina This issue has been fixed in 0.13.0. `is_element_not_present` and `is_element_not_visible` return the moment the element is not present/visible, instead of retrying.
