### ISSUE TITLE
CookieManager.add doesn't accept cookie format supplied by CookieManager.all

### ISSUE THREAD

**Issue by meeotch** [cobrateam/splinter#295]
Browser.cookies.add() doesn't seem to like the cookies returned by Browser.cookies.all().  To reproduce:

```
>> b.visit("http://google.com")
>> acookie = b.cookies.all()[0]
>> acookie
{u'domain': u'.google.com', u'name': u'PREF', u'value': u'ID=d1c9bd113ed75b77:U=edf4f5b25a8ab183:FF=0:TM=1391716688:LM=1391716690:S=VfO-BVRoKQvZKcBX', u'expiry': 1454788681, u'path': u'/', u'secure': False}
>> b.cookies.delete()
>> b.cookies.add(acookie)
>> b.cookies.all()
[{u'domain': u'www.google.com', u'name': u'domain', u'value': u'.google.com', u'expiry': 1896639921, u'path': u'', u'secure': False},
 {u'domain': u'www.google.com', u'name': u'name', u'value': u'PREF', u'expiry': 1896639921, u'path': u'', u'secure': False},
 {u'domain': u'www.google.com', u'name': u'value', u'value': u'ID=7c4c2e6d39468d53:U=51495c50c0c4abd0:FF=0:TM=1391718289:LM=1391718290:S=-ccEkmggULDSHK5w', u'expiry': 1896639921, u'path': u'', u'secure': False},
 {u'domain': u'www.google.com', u'name': u'expiry', u'value': u'1454790282', u'expiry': 1896639921, u'path': u'', u'secure': False},
 {u'domain': u'www.google.com', u'name': u'path', u'value': u'/', u'expiry': 1896639921, u'path': u'', u'secure': False},
 {u'domain': u'www.google.com', u'name': u'secure', u'value': u'false', u'expiry': 1896639921, u'path': u'', u'secure': False}]
```

Note that it sets several cookies, one for each key of the original cookie.  Using instead

```
>> b.cookies.driver.add_cookie(acookie)
```

works as expected.  

Seems like the behavior of the two functions should be consistent, or at least the docs should mention the discrepancy.  As a new user (to both splinter and selenium), it took me a while to figure this out.  I'd think that the simple case of saving a batch (no pun intended) of cookies and re-loading them into the browser should be more intuitive.

**Comment by kalkehcoisa** [comment]
Hi @douglascamata , I know this is an old and closed issue. But, wouldn't be handy to add a method like `cookies.add_all` to be able to directly accept the "dump" done by `cookies.all()`?
Because, you know. It's a very common operation to store the cookies and restore them later.
If it's ok, I send a PR with some code to do so.
