### ISSUE TITLE
WebDriverElement's 'parent' attribute does not work as expected

### ISSUE THREAD

**Issue by ghost** [cobrateam/splinter#297]
In the DOM world 'parent' is a good name for parent element. However, splinter uses that name for browser. Could you use the name 'browser' instead?

```
In [3]: browser = splinter.browser.FirefoxWebDriver()
In [4]: browser.visit('http://google.com')
In [5]: logo = browser.find_by_id('hplogo')
In [6]: logo.parent                                                                                                    
Out[6]: <splinter.driver.webdriver.firefox.WebDriver at 0x1c0a390>       
```

**Comment by ryneeverett** [comment]
I also find this a bit strange but it appears that the selenium bindings have the same peculiarity. The API reference describes [WebElement.parent](http://selenium-python.readthedocs.org/api.html#selenium.webdriver.remote.webelement.WebElement.parent) as:

> Internal reference to the WebDriver instance this element was found from.

**Comment by jsfehler** [comment]
@andrewsmedina Seems like we're following WebDriver's lead here. Changing it would probably cause more confusion than anything else.
