### ISSUE TITLE
Enable custom WebDriver

### ISSUE THREAD

**Issue by hanxue** [cobrateam/splinter#314]
When I run splinter with `Google Chrome Canary` installed, I got this error

```
selenium.common.exceptions.WebDriverException: Message: u'unknown error: cannot find Chrome binary\n  (Driver info: chromedriver=2.10.267517,platform=Mac OS X 10.9.2 x86_64)' 
```

It is possible to configure ChromeWebDriver to use Canary, though splinter currently does not expose this functionality. Expose a `Driver` interface to customize WebDrivers.

**Comment by jsfehler** [comment]
Custom browser paths for chrome can be set via the Chrome Options object:

```
from selenium import webdriver

chrome_options = webdriver.chrome.options.Options()
chrome_options.binary_location = "/path/to/canary"
browser = Browser('chrome', options=chrome_options)
```
