### ISSUE TITLE
403 forbidden using chrome driver.

### ISSUE THREAD

**Issue by whatsdis** [cobrateam/splinter#342]
I keep getting 403 forbidden error on browser.visit

However, if I open another tab in the chromedriver, and I navigate to the url, it loads. 

Where is this coming from and what is causing such behavior?

**Comment by whatsdis** [comment]
I don't think this is the case because when I visit the user agent page, I see the one I defined.

So far regardless of what user agent I use it throws 403 forbidden.

**Comment by andrewsmedina** [comment]
Hi @whatsdis are you using a proxy?

**Comment by whatsdis** [comment]
I am not. but seems to work fine when I use the webdriver instance directly and call `get()`

**Comment by andrewsmedina** [comment]
@whatsdis it is a public url?

**Comment by whatsdis** [comment]
yes

**Comment by andrewsmedina** [comment]
can you share the url. I will try to know what is happen?

**Comment by texom512** [comment]
the user-agent Splinter is "python/splinter" if make that: browser = Browser('phantomjs', user_agent="Mozilla/5.0 (X11; Ubuntu; Linux i686; rv:36.0) Gecko/20100101 Firefox/36.0")
How can I completly change the user agent ?

**Comment by TimurNurlygayanov** [comment]
Why the issue was closed? How to workaround it?

**Comment by TimurNurlygayanov** [comment]
Finaly I've found the workaround:

We need to set a custom user agent to fix 403 errors:

`from selenium import webdriver
from selenium.webdriver.chrome.options import Options
opts = Options()
opts.add_argument("user-agent=whatever you want")

driver = webdriver.Chrome(chrome_options=opts)`

**Comment by Programmer-Admin** [comment]
Hi @TimurNurlygayanov 
Now chrome is having 109 as latest version..what should be the new user agent to use in that case to fix this 403 error?..
Any ideas or thoughts appreciated..
Thanks!
