### ISSUE TITLE
Encoding problem

### ISSUE THREAD

**Issue by Nikodim2010** [cobrateam/splinter#347]
Hello guys! HEre is my problem. When i'm doing this
### 

field = browser.find_by_xpath('//*[@id="ip_form"]/div/div[2]/input')
field.fill('STUFF')
### 

everything is ok, but if I want smth like this:
### 

field = browser.find_by_xpath('//*[@id="ip_form"]/div/div[2]/input')

> > > field.fill("ХУЙ")
> > > Traceback (most recent call last):
> > >   File "<stdin>", line 1, in <module>
> > >   File "C:\Python27\lib\site-packages\splinter\driver\webdriver__init__.py", line 351, in fill
> > >     self.value = value
> > >   File "C:\Python27\lib\site-packages\splinter\driver\webdriver__init__.py", line 338, in _set_value
> > >     self._element.send_keys(value)
> > >   File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webelement.py", line 303, in send_keys
> > >     self._execute(Command.SEND_KEYS_TO_ELEMENT, {'value': typing})
> > >   File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webelement.py", line 385, in _execute
> > >     return self._parent.execute(command, params)
> > >   File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 171, in execute
> > >     response = self.command_executor.execute(driver_command, params)
> > >   File "C:\Python27\lib\site-packages\selenium\webdriver\remote\remote_connection.py", line 346, in execute
> > >     data = utils.dump_json(params)
> > >   File "C:\Python27\lib\site-packages\selenium\webdriver\remote\utils.py", line 30, in dump_json
> > >     return json.dumps(json_struct)
> > >   File "C:\Python27\lib\json__init__.py", line 243, in dumps
> > >     return _default_encoder.encode(obj)
> > >   File "C:\Python27\lib\json\encoder.py", line 207, in encode
> > >     chunks = self.iterencode(o, _one_shot=True)
> > >   File "C:\Python27\lib\json\encoder.py", line 270, in iterencode
> > >     return _iterencode(o, 0)
> > > UnicodeDecodeError: 'utf8' codec can't decode byte 0x95 in position 0: invalid start byte

**Comment by jsfehler** [comment]
This is a python 2 bytes/str issue. Encoding/decoding unicode characters has to be done on the user's end, there's no issue with splinter or selenium.
