### ISSUE TITLE
browser.fill missing numbers

### ISSUE THREAD

**Issue by ajmendez** [cobrateam/splinter#348]
When using the browser.fill() method or browser.type() on a string of numbers, '5' is parsed as a backspace and '6' is parsed as a space or missing.  This works fine on a OSX 10.8 machine but fails on a ubuntu machine:

Code to reproduce problem:

```
import time
from splinter import Browser
browser = Browser('chrome')
browser.visit('http://www.google.com')
browser.fill('q', '0123456789')
# or
# browser.type('q', '0123456789')
# or 
# [time.sleep(0.2) for x in browser.type('q', '0123456789', slowly=True)
```

Expected to find '0123456789' in search bar, found '0123 789'.

Machine information:

```
 Ubuntu 12.04.5 LTS \n \l
 Linux hydrogen 3.2.0-49-generic #75-Ubuntu SMP Tue Jun 18 17:39:32 UTC 2013 x86_64 x86_64      x86_64 GNU/Linux 
 Google Chrome 38.0.2125.104 
 ChromeDriver (v2.11.298611 (d1120fdf51badec2f7b63a96e19a58d4783de84d))
 Python 2.7.3
 Splinter 0.6.0
```

This might be a Chrome / ChromeDriver bug, but I am not sure how to debug this.

**Comment by frodopwns** [comment]
Your test code works for me in Ubuntu 14.04 Python 2.7.6

I downloaded the latest version of the chromedriver  (2.13) and copied it to /usr/bin/ and your script 

    from splinter import Browser
    import time
    browser = Browser("chrome")
    browser.visit('http://www.google.com')
    browser.fill('q', '0123456789')
    time.sleep(5)

resulted in 0123456789 in the search box.

**Comment by whatsdis** [comment]
still happening on Ubuntu 12.04, Python 2.7.x, Splinter 0.7.0, chromedriver 2.13.307, google chrome 39.0.2171

this is super frustrating! can't type passwords with numbers in it.

**Comment by andrewsmedina** [comment]
It looks like a chrome driver bug: https://code.google.com/p/chromedriver/issues/detail?id=435

**Comment by whatsdis** [comment]
damn....I see

**Comment by andrewsmedina** [comment]
This was marked as fixed by chromedriver https://bugs.chromium.org/p/chromedriver/issues/detail?id=627
