### ISSUE TITLE
`html` property doesn't work for multiline elements

### ISSUE THREAD

**Issue by magicjohnson** [cobrateam/splinter#361]
driver: `djangoclient`

element `outer_html` example: 

``` html
<p>\n     some text here\n</p>
```

Traceback:

```
/home/vagrant/virtualenv/local/lib/python2.7/site-packages/splinter/driver/djangoclient.pyc in html(self)
    351     @property
    352     def html(self):
--> 353         return re_extract_inner_html.match(self.outer_html).group(1)
    354
    355     def has_class(self, class_name):

AttributeError: 'NoneType' object has no attribute 'group'
```

I think problem can be easily fixed by using `re.DOTALL`, I can prepare pull request if you wish.

**Comment by andrewsmedina** [comment]
this issue is already fixed the test added in https://github.com/cobrateam/splinter/commit/3bee3089e299f50ef7062b2e1892cd14f03a11f8 proves that
