### ISSUE TITLE
using splinter on a hosted system (like pythonanywhere or wakari)

### ISSUE THREAD

**Issue by jonschull** [cobrateam/splinter#362]
I think I understand that the headless browsers should work for scenarios like running in the cloud (where a firefox or chrome can not be expected).  But I can't get phantomjs or browser('zope.testbrowser') to work on either pythonanywhere or wakari.

Does anyone have a known recipe?

**Comment by bgailer** [comment]
I have same problem.

**Comment by jsfehler** [comment]
This is more of a pythonanywhere question than a splinter question.
