### ISSUE TITLE
browser.quit() an unexpected error occured

### ISSUE THREAD

**Issue by hitigon** [cobrateam/splinter#363]
urlopen error [Errno 49] Can't assign requested address

this error happens for a few webpages, when i am using chrome as the webdriver. it does not happen if the webdriver is phantomjs.

**Comment by andrewsmedina** [comment]
Can you paste the full output?

**Comment by hitigon** [comment]
the full debug output is too large. i put it into my dropbox here: https://www.dropbox.com/s/govjcndqd8yh9lu/log.out?dl=0

I tested many times for two local files (i removed the file addresses in the log). I noticed that in most of cases, when i was using chrome and processing two files at once by multiprocessing, it resulted the url errors. Basically, opening multiple urls/files by splinter.Browser and multiprocessing may cause some issues.
