### ISSUE TITLE
Browser().visit(url),the url have to include  ":"

### ISSUE THREAD

**Issue by isghost** [cobrateam/splinter#364]
> > > path="www.baidu.com"
> > > Browser().visit(path)
> > > Traceback (most recent call last):
> > >   File "<stdin>", line 1, in <module>
> > >   File "c:\users\administrator\appdata\local\enthought\can
> > > ages\splinter-0.7.0-py2.7.egg\splinter\driver\webdriver__
> > > in visit
> > >     self.connect(url)
> > >   File "c:\users\administrator\appdata\local\enthought\can
> > > ages\splinter-0.7.0-py2.7.egg\splinter\request_handler\req
> > >  23, in connect
> > >     self._create_connection()
> > >   File "c:\users\administrator\appdata\local\enthought\can
> > > ages\splinter-0.7.0-py2.7.egg\splinter\request_handler\req
> > >  48, in _create_connection
> > >     self.conn = http_client.HTTPConnection(self.host, self
> > >   File "D:\Enthought\Canopy\App\appdata\canopy-1.5.1.2730.
> > > .py", line 704, in __init__
> > >     self._set_hostport(host, port)
> > >   File "D:\Enthought\Canopy\App\appdata\canopy-1.5.1.2730.
> > > .py", line 723, in _set_hostport
> > >     i = host.rfind(':')
> > > AttributeError: 'NoneType' object has no attribute 'rfind'

**Comment by frodopwns** [comment]
you should include the protocol "http://" in your path

path = "http://www.baidu.com"
