### ISSUE TITLE
/pip install splinter[django] problems

### ISSUE THREAD

**Issue by bgailer** [cobrateam/splinter#371]
C:\Users\bgailer>/python33/scripts/pip install splinter[django]

Following appears several times:

```
Building without Cython.
ERROR: b"'xslt-config' is not recognized as an internal or external command,
```

\r\noperable program or batch file.\r\n"
    *\* make sure the development packages of libxml2 and libxslt are installed *:

At end:

error: Unable to find vcvarsall.bat

---

Cleaning up...
Command c:\python33\python.exe -c "import setuptools, tokenize;**file**='c:\use
rs\bgailer\appdata\local\temp\pip_build_bgailer\lxml\setup.py';exec(compi
le(getattr(tokenize, 'open', open)(**file**).read().replace('\r\n', '\n'), **fil
e**, 'exec'))" install --record c:\users\bgailer\appdata\local\temp\pip-4x3q9q-r
ecord\install-record.txt --single-version-externally-managed --compile failed wi
th error code 1 in c:\users\bgailer\appdata\local\temp\pip_build_bgailer\lxml
Storing debug log for failure in C:\Users\bgailer\pip\pip.log

**Comment by bgailer** [comment]
standard install of python; win 8.1

**Comment by andrewsmedina** [comment]
You should to use the lxml windows binaries for windows: https://pypi.python.org/pypi/lxml

**Comment by matheuscas** [comment]
For me, it does not even works. Here the message that I receive when I type ```pip install splinter[django]```:

```no matches found: splinter[django]```
