### ISSUE TITLE
problem with phantomjs

### ISSUE THREAD

**Issue by bgailer** [cobrateam/splinter#372]
> > > b = Browser('phantomjs')
> > > Traceback (most recent call last):
> > >   File "<interactive input>", line 1, in <module>
> > >   File "C:\Python33\lib\site-packages\splinter\browser.py", line 63, in Browser
> > >     return driver(_args, *_kwargs)
> > >   File "C:\Python33\lib\site-packages\splinter\driver\webdriver\phantomjs.py", line 32, in **init**
> > >     self.driver = PhantomJS(desired_capabilities=capabilities, **kwargs)
> > >   File "C:\Python33\lib\site-packages\selenium\webdriver\phantomjs\webdriver.py", line 50, in **init**
> > >     self.service.start()
> > >   File "C:\Python33\lib\site-packages\selenium\webdriver\phantomjs\service.py", line 74, in start
> > >     raise WebDriverException("Unable to start phantomjs with ghostdriver.", e)
> > > selenium.common.exceptions.WebDriverException: Message: Unable to start phantomjs with ghostdriver.
> > > Screenshot: available via screen

**Comment by bgailer** [comment]
standard install of python; win 8.1

**Comment by andrewsmedina** [comment]
Do you have phantomjs installed?

**Comment by leebrooks0** [comment]
Yeah, the docs don't mention that you have to install it...

**Comment by Florian-Roessler** [comment]
If phantomjs is installed you have to add it to your system path (worked under unix) or pass on the executable when creating the browser object.

**Comment by andrewsmedina** [comment]
@leebrooks0 there is a mention about that "phantomjs" should be installed to use phantom driver: https://splinter.readthedocs.org/en/latest/drivers/phantomjs.html#module-splinter.driver.webdriver.phantomjs

**Comment by bgailer** [comment]
No. That is not correct.Selenium only provides, in the phantomjs folder, webdriver.py.
You also need phantomjs.exe which must be separately downloaded from http://phantomjs.org/.
Please clarify this in the documentation.

**Comment by andrewsmedina** [comment]
@bgailer this is mentioned in the docs:

"PhantomJS is a headless WebKit scriptable with a JavaScript API, to use the driver first you must install it in your machine"

**Comment by bgailer** [comment]
On 5/17/2015 10:16 PM, Andrews Medina wrote:
>
> @bgailer <https://github.com/bgailer> this is mentioned in the docs:
>
> "PhantomJS is a headless WebKit scriptable with a JavaScript API, to 
> use the driver first you must install it in your machine"
>
I realize this is an open source project, so I can't expect anything. 
But I am disappointed that we seem to be in an adversarial relationship.

All I have tried to do is to report the challenges I faced implementing 
phantomjs and offered my recommendation for improved documentation.

What I hearing in essence is "our documentation is fine".

How do you think that leaves me feeling? I struggled to discover the 
facts, got phantomjs working, then offered an improvement to 
documentation that might help other users.

-- 
Bob Gailer
Feline Drover

**Comment by andrewsmedina** [comment]
@bgailer Sorry for this misunderstanding. I believe that splinter documentation is not 100% fine and I agree with you that the documentation should be improved.

So, how we can improve the phantom.js guide? Currently, we have a note about the requirements of the phantom.js and a link to phantom.js instalation page.

Do you think that add a "note box" should fix this problem?

**Comment by bgailer** [comment]
On 5/19/2015 2:18 PM, Andrews Medina wrote:
>
> @bgailer <https://github.com/bgailer> Sorry for this misunderstanding. 
> I believe that splinter documentation is not 100% fine and I agree 
> with you that the documentation should be improved.
>
Thanks
>
> So, how we can improve the phantom.js guide?
>
At http://splinter.readthedocs.org/en/latest/drivers/phantomjs.html I read:

"PhantomJS is a headless WebKit scriptable with a JavaScript API, to use 
the driver first you must install <http://phantomjs.org/download.html> 
it in your machine. The Phantomjs WebDriver is provided by Selenium 2.0, 
thus you need to install Selenium 2.0 via pip"

After much head-scratching and staring at that paragraph I /finally 
/noticed that the word "install" is a link to phantomjs.org.

So indeed the docs are correct /in that part/. Given that it was hard 
for me to see that link I recommend it be made more visible or evident. 
Also the next sentence led me to believe that selenium provided 
phantomjs, so I did not even look for the download link.

Note:
   selenium does /not /provide the phantomjs webdriver.
/webkit /refers to certain browsers. Using webkit here is incorrect.
   phantomjs.exe must be in the executable path in order for subprocess 
to find it.
   as an aside, pip install splinter also installs selenuim.

Suggested revision:

"PhantomJS is a headless scriptable browser with a JavaScript API. To 
use PhantomJS you must install it in your machine. Go to 
http://phantomjs.org/download.html and follow the instructions.

After downloading and unzipping place phantomjs.exe in a folder that is 
included in PATH.

There may be better terminology for PATH in Linux et. al.

-- 
Bob Gailer
Feline Drover

**Comment by andrewsmedina** [comment]
@bgailer thank you, for this suggestion. I will improve the docs. And sorry again for the misunderstanding.
