### ISSUE TITLE
Chromedriver link is out of date

### ISSUE THREAD

**Issue by leebrooks0** [cobrateam/splinter#379]
My tests were failing because I followed the link on the docs, which points to a pretty old version of the driver.

The latest version is here: http://chromedriver.storage.googleapis.com/index.html?path=2.9/

If you want I can fix it and submit a PR?

**Comment by andrewsmedina** [comment]
closed by https://github.com/cobrateam/splinter/commit/b7395821d735c8baf2225408c0001a7675f2b833
