### ISSUE TITLE
User-Agent ignored

### ISSUE THREAD

**Issue by s7726** [cobrateam/splinter#394]
The Browser object accepts a user-agent parameter, then promptly ignores it and jams in 'python/splinter' instead.

This super frustrating fact lead to a ton of time beating my head against a site that refuses to load with that user agent, and wouldn't load even when I provided a real UA string (firefox) for splinter to use.

If I get around to it before someone else does, I'll see if I can tackle this. But would appreciate if someone else has time.

link to location where UA is jammed in:
https://github.com/cobrateam/splinter/blob/master/splinter/request_handler/request_handler.py#L52

**Comment by andrewsmedina** [comment]
In the new splinter version this issue is fixed
