### ISSUE TITLE
element.fill is broken when you give it certain numbers

### ISSUE THREAD

**Issue by whatsdis** [cobrateam/splinter#398]
related https://github.com/cobrateam/splinter/issues/348

element.fill() will delete your characters when string contains '5' or '6'

element.fill('1234567') will result in typing '123 7'

using latest chrome driver, chrome browser, 0.7.0 splinter, python 2.7.x., ubuntu 12.04

**Comment by andrewsmedina** [comment]
I believe that use webdriver `elem.send_keys` instead `elem.value` will fix this problem.

**Comment by whatsdis** [comment]
same result with elm.send_keys. haven't tried elm.value

**Comment by andrewsmedina** [comment]
It looks like a chrome driver bug: https://code.google.com/p/chromedriver/issues/detail?id=435

**Comment by andrewsmedina** [comment]
This was marked as fixed in chromedriver https://bugs.chromium.org/p/chromedriver/issues/detail?id=627
