### ISSUE TITLE
Splinter can not access website which only can access through proxy

### ISSUE THREAD

**Issue by angleBeibei** [cobrateam/splinter#399]
When splinter access website which only can access through proxy, a exception is throwed. Through analysis source, I found that splinter use  HTTPConnection access website without proxy,if this access is success, splinter can use phantomjs with proxy; if failure access, splinter throw exception and quit.

**Comment by andrewsmedina** [comment]
I believe that this issue is related to #241. What driver are you using?

**Comment by andrewsmedina** [comment]
Splinter don't do the addition request to get `status_code` data. So I believe that this issue is fixed.
