### ISSUE TITLE
Can't access outer iframe after accessing nested iframe in context manager

### ISSUE THREAD

**Issue by adambrenecki** [cobrateam/splinter#411]
Hi,

I'm trying to use Splinter automate something on a site that's structured something like this:

```
top level page
| iframe
| | iframe
| | | form widgets
| | submit button
```

(This is exactly as fun as it looks, by the way.)

If I write my code like this:

``` python
    with browser.get_iframe('outerframe') as outer_iframe:
        with outer_iframe.get_iframe('innerframe') as iframe:
            iframe.find_by_id('field1').first.fill('value')
            iframe.find_by_id('field2').first.fill('value')

        outer_iframe.find_by_id('button').first.click()
```

I get an exception like this:

```
splinter.exceptions.ElementDoesNotExist: no elements could be found with id "button"
```

But if I write my code like this, it works:

``` python
    with browser.get_iframe('outerframe') as outer_iframe:
        with outer_iframe.get_iframe('innerframe') as iframe:
            iframe.find_by_id('field1').first.fill('value')
            iframe.find_by_id('field2').first.fill('value')

    with browser.get_iframe('outerframe') as outer_iframe:
        outer_iframe.find_by_id('button').first.click()
```

(As an aside, Splinter is amazing, it's made my life a lot easier today, thanks!)

**Comment by norm** [comment]
If those code samples are exact, there is a difference between the value of `outer_iframe` when you try to click the button between the two. In the one that works it is the value of `browser.get_iframe('innerframe')`, in the one that doesn't it is the value of `browser.get_iframe('outerframe')`.

**Comment by adambrenecki** [comment]
Oops; I changed the iframe IDs to try to make it less obvious which website I'm scraping, and I must have messed that up. I've fixed that error in the code above.
