### ISSUE TITLE
Problem with specific use case, with xpath

### ISSUE THREAD

**Issue by v1gnesh** [cobrateam/splinter#416]
Hola,

I'm trying to scrape content off of the HP warranty check page (h20564.www2.hp.com/hpsc/wc/public/home). 
I found a way to fill a form and go to the next page, where I get nested tables.

Here's the xpath for the item I'm interested in. 

/html/body/div[@id='everything']/div[@id='content']/div[@id='body']/div/table/tbody/tr/td[3]/table/tbody/tr[2]/td/div/form[@id='warrantyCheck']/table[@class='hpui-padding-top-10']/tbody/tr[2]/td[@id='generate_table_yourSerialNumber']/table[@class='hpui-standard-table']/tbody/tr[@class='hpui-normal-row'][1]/td[5]

I've checked the xpath with both _xpath helper_ (chrome extension to GET xpath) and _xpather_ (chrome extension to TEST xpath validity), and it works alright.

I've saved the xpath to the variable item2. The line of code that's causing the issue:
print browser.find_by_xpath(item2).first.text

However, the program fails with this:

Traceback (most recent call last):
  File "splintest.py", line 50, in <module>
    print browser.find_by_xpath(item2).first.text
  File "C:\Python27\lib\site-packages\splinter\element_list.py", line 53, in fir
st
    return self[0]
  File "C:\Python27\lib\site-packages\splinter\element_list.py", line 44, in **g
etitem**
    self.find_by, self.query))
splinter.exceptions.ElementDoesNotExist: no elements could be found with xpath "
//html/body/div[@id='everything']/div[@id='content']/div[@id='body']/div/table/t
body/tr/td[3]/table/tbody/tr[2]/td/div/form[@id='warrantyCheck']/table[@class='h
pui-padding-top-10']/tbody/tr[2]/td[@id='generate_table_mySerialNumber']/table[@clas
s='hpui-standard-table']/tbody/tr[@class='hpui-normal-row']/td[2]"

Anyone with a HP product to check warranty against, I could really, really use some help!

**Comment by alex-deas** [comment]
Two issues I can see with the xpath here:
1) When viewing the site the final tr class '/tr{@class="hpui-normal-row"]' is not there. Could be worth trying without that class?
2) Only 4 td contained within the previously mentioned  tr (the inputs for 'serial number' and 'country') whereas your xpath refers to the 5th.

Unless you're seeing something different to me, these need to be addressed first.
