### ISSUE TITLE
Browser (WebDriver) has no attribute 'find_by_text'

### ISSUE THREAD

**Issue by svicalifornia** [cobrateam/splinter#418]
The documentation says that Splinter has a `find_by_text` method:

https://splinter.readthedocs.org/en/latest/finding.html

But it doesn't:

```
browser = Browser('chrome')
browser.visit('http://daringfireball.net')
browser.find_by_text('John Gruber')  # AttributeError: 'WebDriver' object has no attribute 'find_by_text'
```

This method would be very useful. Please add it.

**Comment by miketonks** [comment]
+1

Looks like this is fixed in master but not on 0.7.2 release:

https://github.com/cobrateam/splinter/commit/5829708d5f0392b4f61358d6a1e088c008391567

Any chance of a new release so we can get this fix?

**Comment by chausies** [comment]
+1

Please fix this soon T~T <3. Any simple way of getting around this with a better installation?

**Comment by chausies** [comment]
A workaround for installing the master version is this:

sudo pip install git+git://github.com/cobrateam/splinter.git

Make sure to uninstall your previous instillation beforehand with pip uninstall

**Comment by andrewsmedina** [comment]
I will make a new splinter release :)

**Comment by garrettedwards95** [comment]
Any word on when we will see a new release with support for `find_by_text`?
