### ISSUE TITLE
Custom firefox profile doesn't work in Windows

### ISSUE THREAD

**Issue by endolith** [cobrateam/splinter#422]
[Documentation](http://splinter.readthedocs.org/en/latest/drivers/firefox.html#how-to-use-a-specific-profile-for-firefox) says you can select an existing firefox profile instead of creating a temporary one each time:

```
browser = Browser('firefox', profile='my_profile')
```

But this doesn't actually work, it doesn't know where to search for the profile:

```
browser = Browser('firefox', profile='default')
...
WindowsError: [Error 3] The system cannot find the path specified: 'default/*.*'
```

same for `profile='272kp1a1.default'`, `profile='272kp1a1'`, etc. though it isn't explained in the docs which type of string is correct.

**Comment by andrewsmedina** [comment]
@endolith what is your windows, firefox and splinter version?

**Comment by endolith** [comment]
I'll check exact numbers later, but it's Windows 7 Pro 64-bit, the version currently installed by `pip install splinter` (0.7.2?), and the latest version of firefox (39?).  Both were installed yesterday.  Python is python(x,y)-2.7.10.0

**Comment by AndCycle** [comment]
the workaround is not working at all, the profile parameter is never get pass down to commandline.
