### ISSUE TITLE
Why find_by_id returns ElementList?

### ISSUE THREAD

**Issue by zakuro9715** [cobrateam/splinter#424]
find_by_id returns ElementList now. But return value of find_by_id should has 1 or 0 element because id is unique in a page.

So I think that find_by_id should return ElementAPI(or None when element not found).

Don't you think first code is more readable that second one?. 
```py
element = browser.find_by_id('#id')
if element:
    element.click()
```
```py
element_list = browser.find_by_id('#id')
if not element_list.is_empty():
    element_list.first.click()
```

**Comment by andrewsmedina** [comment]
@zakuro9715 all `find_by` methods return a `ElementList`. But if you want to use the first element you don't need to use the `first` attribute.

`element_list.click` does the same that `element_list.first.click()` : https://github.com/cobrateam/splinter/blob/master/splinter/element_list.py#L70

**Comment by zakuro9715** [comment]
@andrewsmedina Thank you very much! Please close this issue.
