### ISSUE TITLE
Specify firefox extension not working

### ISSUE THREAD

**Issue by kkzhang** [cobrateam/splinter#427]
https://github.com/cobrateam/splinter/blob/master/docs/drivers/firefox.rst#how-to-use-specific-extensions-for-firefox

I followed the instruction but unlucky it's not working, firefox has installed xpi but the extension is not working as expect then.

![image](https://cloud.githubusercontent.com/assets/575834/9189396/752af0b0-401a-11e5-8069-1ffcd9850c7e.png)

![2015-08-11 11 17 42](https://cloud.githubusercontent.com/assets/575834/9189422/d4a4b454-401a-11e5-9f1b-55990c0e9d28.png)

OS: mac 10.10.4
splinter: (0.7.2)

**Comment by jsfehler** [comment]
@andrewsmedina This is a selenium issue: 

https://github.com/SeleniumHQ/selenium/issues/7677
https://github.com/SeleniumHQ/selenium/issues/6548

As noted in that ticket: `driver.install_addon()` is a workaround.

**Comment by burner1024** [comment]
Sorry, could you provide a complete snippet of loading? I looked all lover, but can't find how to access selenium's `instal_addon` from Splinter API.
