### ISSUE TITLE
Firefox driver not found

### ISSUE THREAD

**Issue by jbabuino** [cobrateam/splinter#431]
When using Firefox, installed with brew cask, splinter can't find the executable:

OSError: [Errno 2] No such file or directory

**Comment by andrewsmedina** [comment]
@jbabuino firefox bin is on the $PATH?

**Comment by pquentin** [comment]
No, it's not. `brew cask install firefox` does not put firefox in the $PATH.

`export PATH=/opt/homebrew-cask/Caskroom/firefox/latest/Firefox.app/Contents/MacOS/:$PATH` would do, but there's probably something cleaner.

**Comment by jbabuino** [comment]
Yes, that was the problem! Thanks :)
