### ISSUE TITLE
Firefox 41 workaround: Unable to connect to host 127.0.0.1 on port 7055 after 45000 ms

### ISSUE THREAD

**Issue by miohtama** [cobrateam/splinter#432]
Firefox 41 allows only installation of signed extensions. Selenium does not have a signed extension available yet. Running Splinter on Firefox 41 fails with `Unable to connect to host 127.0.0.1 on port 7055 after 45000 ms`

You can make Firefox to work again by dropping:

       firefox_profile.set_preference('xpinstall.signatures.required', False)

to  `firefox.py`.

This workaround won't work for Firefox 42.

More information

* https://github.com/SeleniumHQ/selenium/issues/927

* https://github.com/SeleniumHQ/selenium/issues/901

Just for your information. I guess this issue can be closed when Selenium gets a proper release.

**Comment by modernnitwit** [comment]
Great! This works for me. Big thanks :+1:

**Comment by miohtama** [comment]
I think the latest Selenium releases have fixed this bug, so this should be closed if anyone can confirm this. `pip install -U Selenium` should be enough.

**Comment by lukeholder** [comment]
> I think the latest Selenium releases have fixed this bug

Confirmed, I see the error on 2.45.0 but after upgrading Selenium to 2.49.x the issue is fixed.
