### ISSUE TITLE
fill() doesn't work when element without attribute name

### ISSUE THREAD

**Issue by gxy501** [cobrateam/splinter#434]
browser.fill('password','12345678') doesn't work with <input class="logininput me-margin-bottom10" type="password" id="password" tabindex="2">

**Comment by douglascamata** [comment]
You can use a selector to find your element and use it method `fill` of the `ElementAPI`. 
```python
browser.find('.my_class').first.fill('12345678')
```

**Comment by gxy501** [comment]
Thank you
it works well with ElementAPI
