### ISSUE TITLE
trouble with the unit tests that are run for every pull request.

### ISSUE THREAD

**Issue by Woozinator** [cobrateam/splinter#449]
I tried to help improving splinter by applying a patch and sending a pull request. This is the first time a try to commit something to a project on github, so please be gentle. ;)

After creating the pull request, most of the automated tests failed and I've got no clue what to do now. I'm pretty sure I didn't break the tests, because I only added one optional parameter and nothing is supposed to change, if the parameter is not used.

This is my fork: 
https://github.com/Woozinator/splinter/tree/patch-1

**Comment by hltbra** [comment]
I don't think it's your fault, @Woozinator. The build was already broken before your commit. I will add a comment to the pull request. Feel free to close this issue.

**Comment by Woozinator** [comment]
Thank you :)
