### ISSUE TITLE
find_by_* cannot find ajax result

### ISSUE THREAD

**Issue by halent** [cobrateam/splinter#451]
i  am a new user of this tool, it's so cool 
but 
when the "Browser.html" doesnot have the ajax part 
i can  use the is_element_present_by_\*  to chech if  the 'ajax' element  is present
but 
i want to click the 'ajax' part,such as button or href
hope u can understand my 'chinese' english 
么么哒
finance_h@163.com

**Comment by andrewsmedina** [comment]
@halent you can use find_by if is_element_present returns True
