### ISSUE TITLE
Firefox 43 workaround:Unable to connect to host 127.0.0.1 on port 7055 after 45000 ms

### ISSUE THREAD

**Issue by sundarasubbiah** [cobrateam/splinter#458]
Firefox 43 in windows 10 does not allow Selenium -Server-Standalone-2.48.2 and it gets fail with  Unable to connect to host 127.0.0.1 on port 7055 after 45000 ms.

I am getting Error when I tried this:

public static void main(String[] args) {
		// TODO Auto-generated method stub
		    WebDriver driver = new FirefoxDriver();
			String URL="https://www.redbus.in/";
			driver.get(URL); 
			String currentURL = driver.getCurrentUrl(); 
			System.out.println("Current URL is "+currentURL);
			String pageTitle = driver.getTitle(); 
			System.out.println("Current pageTitle is "+pageTitle); 
			driver.getTitle(); 
			driver.manage().window().maximize();

Error shown in console:

org.openqa.selenium.firefox.NotConnectedException: Unable to connect to host 127.0.0.1 on port 7055 after 45000 ms. Firefox console output:
xpi	DEBUG	checkForChanges
1451449673235	addons.xpi

**Comment by andrewsmedina** [comment]
Are you using splinter or are just using selenium?

**Comment by sundarasubbiah** [comment]
only Selenium i am using..

**Comment by andrewsmedina** [comment]
@sundarasubbiah that the better place to open an issue about this problem is the selenium project: https://github.com/SeleniumHQ/selenium. With a quick look in the selenium issue I found it: https://github.com/SeleniumHQ/selenium/issues/1350

**Comment by Jiharka** [comment]
I am new here, and I dont know were I should  leave information about the same issue: when use latest FF 45.0.1 and Selenium 2.53.0 I have the same error, BUT it works fine with FF 44.0.2 and Selenium 2.53.0

**Comment by viveksalve** [comment]
when use latest FF 45.0.1 and Selenium 2.53.0 I have the same error, BUT it works fine with FF 44.0.2 and Selenium 2.53.0

**Comment by bjdevil21** [comment]
I was using Behat with Selenium 2.46.0 and was getting the error with FF 46.0 64-bit in Linux.

After I updated to Selenium to 2.53.0 (from v2.46.0), and it started working again.
