### ISSUE TITLE
ENH: ./nb/000-splinter-notebooks.py.ipynb: Jupyter notebooks for Splinter

### ISSUE THREAD

**Issue by westurner** [cobrateam/splinter#459]
- GitHub renders .ipynb files (*currently only w/ the desktop interface)
- Nbviewer renders .ipynb files

**Comment by andrewsmedina** [comment]
@westurner  I did not understand what this issue is about. can you elaborate? thank you

**Comment by westurner** [comment]
Would it be useful to write and PR jupyter notebook[s] in a top-level ``./nb`` directory?

**Comment by westurner** [comment]
... The [docs] Makefile then would have a step like:

```make
buildnbs:
  # build jupyter notebooks for :docs
  findnbs | makeindex.py --readme > README.rst
  findnbs | makeindex.py --html > index.html
  findnbs | xargs -I% jupyter-nbconvert --to html %
  findnbs | xargs -I% jupyter-nbconvert --to python %

```

**Comment by westurner** [comment]
Sort of like https://github.com/westurner/notebooks/blob/gh-pages/makeindex.py ... I should really factor this out ... - [ ] REF: makeindex.py -> [projectname]

**Comment by jsfehler** [comment]
Closing due to lack of clarity and inactivity.
