### ISSUE TITLE
Is it possible to use Splinter on Digital Ocean?

### ISSUE THREAD

**Issue by thebasix** [cobrateam/splinter#466]
Is it possible to use Splinter on Digital Ocean on Ubuntu without GUI and how?

**Comment by douglascamata** [comment]
@thebasix you should use xvfb to start a virtual display and it will work.

**Comment by kz** [comment]
@douglascamata @thebasix Running Splinter is working in Vagrant + headerless Ubuntu. I'm using PhantomJS (Selenium) as the driver though.

**Comment by andrewsmedina** [comment]
There are two was to run tsuru without display:

* xvfb: is a display server implementing the X11 display server protocol. You can use pyvirtualdisplay as xvfb python wrapper: http://pyvirtualdisplay.readthedocs.org/en/latest/
* using a headless driver: phantomjs, zope.webdriver, djangoclient or flaskclient
