### ISSUE TITLE
django driver error

### ISSUE THREAD

**Issue by patommel** [cobrateam/splinter#467]
Would someone be able to help diagnose this error message when attempting to use the django driver on windows 10? Django, lxml and cssselect are installed and up to date

`Traceback (most recent call last):`
`File "C:\Users\ME\SCRIPT.py", line 7, in <module>`
`browser.visit(url)`
`File "C:\Python27\lib\site-packages\splinter\driver\djangoclient.py", line 116, in visit`
`self._response = self._browser.get(url, follow=True, **extra)`
`File "C:\Python27\lib\site-packages\django\test\client.py", line 503, in get`
`**extra)`
`File "C:\Python27\lib\site-packages\django\test\client.py", line 304, in get`
`return self.generic('GET', path, secure=secure, **r)`
`File "C:\Python27\lib\site-packages\django\test\client.py", line 359, in generic`
`data = force_bytes(data, settings.DEFAULT_CHARSET)`
`File "C:\Python27\lib\site-packages\django\conf\__init__.py", line 55, in __getattr__`
`self._setup(name)`
`File "C:\Python27\lib\site-packages\django\conf\__init__.py", line 41, in _setup`
`% (desc, ENVIRONMENT_VARIABLE))`
`django.core.exceptions.ImproperlyConfigured: Requested setting DEFAULT_CHARSET, but settings are not configured. You must either define the environment variable DJANGO_SETTINGS_MODULE or call settings.configure() before accessing settings.`

**Comment by drernie** [comment]
It doesn't sound like it can not find your settings file.  What command are you using to run your module?
