### ISSUE TITLE
phantomjs click user_agent

### ISSUE THREAD

**Issue by wenson** [cobrateam/splinter#469]
use the  phantomjs ，

browser = Browser('phantomjs',user_agent="Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.109 Safari/537.36")

browser.find_by_tag('a').first.click() 

BUT
 the user-agent of the newly opened page is not my set.

**Comment by bmcculley** [comment]
I'm not able to reproduce this, user_agent is set as expected.

Here's the code I used to test

```
from splinter import Browser

with Browser('phantomjs', user_agent='my user agent string') as browser:
    url = "http://www.whatsmyua.com/"
    browser.visit(url)
    if browser.status_code.is_success():
        browser.driver.save_screenshot('screenshot.png')
    else:
        print('page failed to load.')
    browser.quit()
```
