### ISSUE TITLE
'select' method : xpath for finding target option fails when using optgroup

### ISSUE THREAD

**Issue by stewbawka** [cobrateam/splinter#470]
Current xpath the select uses:
'//select[@name="%s"]/option[@value="%s"]' % (self["name"], value)
This fails when select tag uses nested optgroups. 

Suggestion: xpath for find option could be made more robust as follows:
'//select[@name="%s"]//option[@value="%s"]' % (self["name"], value)

**Comment by jsfehler** [comment]
This appears to have been fixed by #334
