### ISSUE TITLE
how manage window popups ?

### ISSUE THREAD

**Issue by ovnicraft** [cobrateam/splinter#473]
i am testing splinter (looks really good) and my issue comes here: 
My code https://gist.github.com/ovnicraft/2c46ebc0663d8084e7c7

You can check the site and click manually on "Ingresar", you will see how site open a popup.
My script give this traceback https://gist.github.com/ovnicraft/2f1662b7c6c014da938b, looking for element krd. 

if you debug manually popup opened you can confirm krd is the name of input to login.

How manage this in browser variable ?

**Comment by afgonzalezgarcia** [comment]
Hi ovnicfaft. The problem is that this link doesn't open a popup, it opens a new windows.

I review it and i have found that  the url to the new window is: http://www.gestiondocumental.gob.ec/login.php

Then, you can go directly to this url to do you log in
browser.visit("http://www.gestiondocumental.gob.ec/login.php") and it'll be fine

Regards

**Comment by douglascamata** [comment]
You have 2 options:

1. Visit the login url directly (`http://www.gestiondocumental.gob.ec/login.php`)
2. Use the `browser.windows.current().next` to change to the new window. More information about this at: https://github.com/cobrateam/splinter/blob/master/tests/popups.py

**Comment by ovnicraft** [comment]
Thanks for your comments, so before test it, if you check /login.php if its access directly from browser redirect to index.php.

Will comment results.

**Comment by ovnicraft** [comment]
so browser.windows list has the window /login.php, so i get: 
`login = browser.windows[1]`
`login.fill(args)`

ipdb> browser.windows.current.next.fill()
*** AttributeError: 'Window' object has no attribute 'fill'

So, browser.windows.current.next does not activate window as current.

**Comment by douglascamata** [comment]
You should do something like:

```python
browser.visit(url)
browser.find_by_id('boton ingreso').click()

browser.windows.current = browser.windows.current.next
browser.do_stuff()
```
This will work in case the pop-up isn't focussed upon opening, you should check if it works. You will not interact with the Window object, you just use it to change the `browser.windows.current` attribute and then interact with the Browser object.

**Comment by ovnicraft** [comment]
@douglascamata thanks for info, working now.
