### ISSUE TITLE
six package must be installed to Django Client works

### ISSUE THREAD

**Issue by matheuscas** [cobrateam/splinter#474]
In [Django Client session](https://splinter.readthedocs.org/en/latest/drivers/django.html) it says that **you need to install django, lxml and cssselect.** But you need to install six package as well. I realised that in django 1.8.11 where it does not install this package automatically.

**Comment by drernie** [comment]
When you install it, do you see a deprecation warning?
```
/Users/ernest/Developer/solrates/lib/python2.7/site-packages/six.py:808: RemovedInDjango110Warning: SubfieldBase has been deprecated. Use Field.from_db_value instead.
  return meta(name, bases, d)
```

**Comment by matheuscas** [comment]
Not at all.
