### ISSUE TITLE
webdriver remote driver does not support doubleclick

### ISSUE THREAD

**Issue by howaryoo** [cobrateam/splinter#475]
Hi all,

any info on what adding support for a doubleclick would be greatly appreciated.

Regards.

splinter/driver/webdriver/remote.py
52:        Remote Firefox doesn't support doubleclick.
54:        raise NotImplementedError("Remote Firefox doesn't support doubleclick")

**Comment by oobibigo** [comment]
why not just click two times!

**Comment by jsfehler** [comment]
Fixed in splinter 0.12.0
