### ISSUE TITLE
Some splinter functions are not working

### ISSUE THREAD

**Issue by AviSub** [cobrateam/splinter#491]
Hi All,

I am using splinter to do some web testing on chrome , I have 2 different scenarios that I am trying to do but nothing happened.

This is the code i am using:

```
import splinter
browser = splinter.Browser('chrome')
browser.visit (‘http://URL/url.com’)
browser.choose('Period','Day')
browser.select('fromstatsday_sday', '03')
```
1. When choosing the radio by name nothing happened (See link) 
   [https://drive.google.com/open?id=0B3gWFncJ_UJfM2ZyMjJjWUowWVE](url)

2.When trying to select the checkbox and the "from day" "03" nothing happen (See link)
[https://drive.google.com/open?id=0B3gWFncJ_UJfc3lzNlVBUVBBSmc](url)

I guess i am doing something wrong, I am new with splinter.... So any suggestions ?

**Comment by andrewsmedina** [comment]
Can you paste the html structure?

**Comment by AviSub** [comment]
This is an internal server

**Comment by andrewsmedina** [comment]
I need the html to try to reproduce, if you want you can paste a similar html data.

**Comment by AviSub** [comment]
[https://drive.google.com/folderview?id=0B3gWFncJ_UJfV19Pak42MGwwejA&usp=sharing](url)
I hope this link will help

**Comment by AviSub** [comment]
Any update on this? did the html helped to investigate this ?

**Comment by AviSub** [comment]
Can someone suggest on this?

**Comment by jsfehler** [comment]
@andrewsmedina Given the age of this issue and nobody else raising it, I think it's best to kick it out of 1.0 and close.
