### ISSUE TITLE
Need to control chromedriver chrome language, but chrome_options can't be passed along

### ISSUE THREAD

**Issue by BuhtigithuB** [cobrateam/splinter#492]
Hello,

Try to use chrome instead of firefox as it is faster and because firefox stop working recently for apparently selenium/splinter/firefox update missmatch of some kind...

I have ubuntu with french locales and chrome seems to be installed with french as a default language... My tests need to be executed in us-en chrome instance to succeed. Even if I set default language to us_en in chrome preferences the instance lauched by browser('chrome') don't seems to use the default profile preferences but the chrome built one or something.

So, I try many way to pass language specification to chrome instance without succes.

1)

``` python
    from splinter.driver.webdriver.chrome.Options import Options
    import splinter
    options = splinter.driver.webdriver.chrome.Options()
    options.add_argument('--lang=en-us')
    browser = Browser('chrome', chrome_options=options)
```

Inspire by some answer from this SO question : http://sqa.stackexchange.com/questions/9904/how-to-set-browser-locale-with-chromedriver-python

Not working...

2)

``` python
    from selenium.webdriver import Chrome
    from selenium.webdriver.chrome.options import Options
    from splinter.driver.webdriver import BaseWebDriver, WebDriverElement

    options = Options()
    options.add_argument('--lang=en-us')
    global browser
    browser = BaseWebDriver()
    browser.driver = Chrome(chrome_options=options)
```

This other option failed with the following error : 

> ```
>   do_login_if_need(username, base64.b64decode(password))
> ```

controllers/test_analysis.py:180: 
controllers/test_analysis.py:90: in do_login_if_need
    if browser.is_element_present_by_css('div.login_box'):
/usr/local/lib/python2.7/dist-packages/splinter/driver/webdriver/**init**.py:251: in is_element_present_by_css
    return self.is_element_present(self.find_by_css, css_selector, wait_time)
/usr/local/lib/python2.7/dist-packages/splinter/driver/webdriver/**init**.py:237: in is_element_present
    if finder(selector):
/usr/local/lib/python2.7/dist-packages/splinter/driver/webdriver/**init**.py:387: in find_by_css
    original_query=css_selector)

self = <splinter.driver.webdriver.BaseWebDriver object at 0x7fd3bc2b8d90>
finder = <bound method WebDriver.find_elements_by_css_selector of <selenium.webdriver.chrome.webdriver.WebDriver (session="e32ee751b41d469e5138fac42c7d25e4")>>, selector = 'div.login_box', original_find = 'css'
original_query = 'div.login_box'

```
def find_by(self, finder, selector, original_find=None, original_query=None):
    elements = None
    end_time = time.time() + self.wait_time

    func_name = getattr(getattr(finder, _meth_func), _func_name)
    find_by = original_find or func_name[func_name.rfind('_by_') + 4:]
    query = original_query or selector

    while time.time() < end_time:
        try:
            elements = finder(selector)
            if not isinstance(elements, list):
                elements = [elements]
        except NoSuchElementException:
            pass

        if elements:
            return ElementList(
```

> ```
>               [self.element_class(element, self) for element in elements],
>                 find_by=find_by, query=query)
> ```
> 
> E               AttributeError: 'BaseWebDriver' object has no attribute 'element_class'

/usr/local/lib/python2.7/dist-packages/splinter/driver/webdriver/**init**.py:380: AttributeError

I am not sure if It is me that don't follow proper API fo BaseWebDriver or if the issue is somewhere else...

I think issues #326 and #382 are relate to mine...

Thanks

**Comment by BuhtigithuB** [comment]
Changing system settings for english usa allow me to work around test extecution... But I would greatly prefer be able to specify language of chrome instance.

Thanks

**Comment by nicolasunravel** [comment]
try with latest master, should now work

**Comment by BuhtigithuB** [comment]
Can you tell how chrome options should be passed? Neither of both way I detailed above work...

I am not sure that sudo python setup.py install had override or not version install by pip though...

Thanks

**Comment by bmcculley** [comment]
I don't believe it's currently possible to do this from the command line arguments. The "--lang=" flag only changes the language file loaded and not the Accept-Language header passed by the browser.

See the following links:

- http://peter.sh/experiments/chromium-command-line-switches/#lang
- https://cs.chromium.org/chromium/src/ui/base/ui_base_switches.cc?q=kLang&sq=package:chromium&type=cs&l=51
- http://stackoverflow.com/a/24992503

**Comment by BuhtigithuB** [comment]
Still struggle to search a solution for this... Best ressources so far : http://stackoverflow.com/questions/11289597/webdriver-how-to-specify-preferred-languages-for-chrome

I am trying to use the proposed workaround in the last comment to the accepted answer where c089 propose this gist : https://gist.github.com/c089/a5cbb834f9b54004de9b

The example is in java, will try to make it work in python and report back here...

**Comment by karlwnw** [comment]
Hi @BuhtigithuB,

A bit late, but just in case you still need it, I found that `options.add_experimental_option("prefs", {"intl.accept_languages": "fr-FR"})` works.

Karl

**Comment by BuhtigithuB** [comment]
I know, I create this gist 9 months ago : https://gist.github.com/BuhtigithuB/11df8cf8d03bb236985156de204fe7b4

**Comment by kriom** [comment]
Hi,

Now `options.add_option("prefs", {"intl.accept_languages": "fr-FR"})` can used

Thanks

**Comment by aramgrigoryan** [comment]
Hi, still running from germany to query english questions on google . com returns answers in german, not in english as expected...
options are
```
chrome_options = Options()
chrome_options.add_argument("--window-size=1024x768")
chrome_options.add_argument("--headless")
chrome_options.add_argument("--lang=en-us")
chrome_options.add_experimental_option('prefs', {'intl.accept_languages': 'en-US'})
driver = webdriver.Chrome(chrome_options=chrome_options)
```

**Comment by Loschcode** [comment]
In Ruby, I used it this way if that can help anyone

```
  BROWSER_LANGUAGE = 'el' # could be en-US, fr-FR, etc.
  options = Selenium::WebDriver::Chrome::Options.new
  options.add_option('prefs', 'intl.accept_languages': BROWSER_LANGUAGE)

  Capybara::Selenium::Driver.new(
    app,
    browser: :chrome,
    desired_capabilities: capabilities,
    http_client: client,
    options: options
  )
```
