### ISSUE TITLE
[FR] a click_link_by_id function would be good

### ISSUE THREAD

**Issue by GeorgeFischhof** [cobrateam/splinter#493]
Hi There,

 a click_link_by_id() function would be good, 
As I feel splinter behaves in different way if click_link... is called than just click_by... is called

BR,
George

**Comment by otherpirate** [comment]
Hi @GeorgeFischhof, 

I think it will help you #498 

Thanks @andrewsmedina

**Comment by GeorgeFischhof** [comment]
Hi @otherpirate,

As I see the code click_link_by_id()  exactly the same as find_by_id().click()
Is it true? (I thought that there is a difference between click...() and click_link...() functions in logic. I thought that click_link...() waits for page loading after clcik.)

BR,
George
