### ISSUE TITLE
No easy way to set Firefox startup timeout

### ISSUE THREAD

**Issue by rlafuente** [cobrateam/splinter#495]
Sometimes, Selenium's default timeout for launching Firefox (30 secs) is not enough, resulting in a cryptic error about not being able to load the profile. I got out of this by directly editing the `selenium/webdriver/firefox/webdriver.py` file and changing the default, but this is a brittle solution.

It would make sense to be able to specify, within Splinter, the "timeout" argument to the Selenium webdriver launcher. Something like

```python
browser = Browser('firefox', firefox_launch_timeout=90)
```

**Comment by douglascamata** [comment]
In which way did you have to modify it?

**Comment by rlafuente** [comment]
I had edited the Selenium code directly for my purposes when I posted the issue, but looked into it and went with your suggestion to fix Splinter itself. See PR #503
