### ISSUE TITLE
Firefox forces stop

### ISSUE THREAD

**Issue by sprajosh** [cobrateam/splinter#496]
Every time I try to open a Firefox browser, it forces close. This happens to Firefox and Firefox Developer Edition. Chrome works fine. I'm not really sure why this happens or if this happens to all.
I hope somebody looks into it!

**Comment by douglascamata** [comment]
Which Firefox version?

**Comment by sprajosh** [comment]
Version: 47.0
PS: I have checked this with recent updates only.

**Comment by douglascamata** [comment]
Can you check Selenium version too?

It looks like you need to update to Firefox 47.0.1: https://github.com/SeleniumHQ/selenium/issues/2110

**Comment by sprajosh** [comment]
Selenium Version: 2.47.1
Firefox Version: 47.0

I'll update both and let you know :)
