### ISSUE TITLE
Is there a next release planned?

### ISSUE THREAD

**Issue by Lawouach** [cobrateam/splinter#497]
Hi there,

I've started using splinter for my tests and it's proven to be very handy. But one thing that is a little frustrating is that the docs are wired to the latest state of the code while the current stable release dates from a year ago.

Some of the parameters aren't the same anymore when it comes to initialize drivers.

Is there something holding up a new release? :)

Thanks!

**Comment by andrewsmedina** [comment]
I believe that we can make a new release. I will try to do it until weekend

**Comment by Lawouach** [comment]
Thanks @andrewsmedina. Whenever that's workable for you will do. For now, I'm relying git pulling master from github directly. But, I would obviously prefer an officially tagged release at some point.

**Comment by andrewsmedina** [comment]
0.7.4 released https://github.com/cobrateam/splinter/releases/tag/0.7.4

**Comment by Lawouach** [comment]
Brilliant! Thanks :)
