### ISSUE TITLE
add MarionetteDriver support

### ISSUE THREAD

**Issue by bubenkoff** [cobrateam/splinter#505]
The WebDriver component which handles Firefox browsers (FirefoxDriver) will be discontinued
so can you please change the behaviour of Browser('firefox') to use MarionetteDriver?
Thanks!

**Comment by jefsayshi** [comment]
You can get Marionette driver support already in version 0.7.4 thru:
- Selenium capabilities for Firefox driver (https://github.com/cobrateam/splinter/pull/417).

Here are the steps that I had to take
- Download the appropriate geckodriver (https://github.com/mozilla/geckodriver/releases)
- Place geckodriver in a location specified by your PATH variable
- Symlink geckodriver to wires `ln -s geckodriver wires`
- Use the following code (change to your firefox binary location):
```python
from splinter import Browser
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities


caps = DesiredCapabilities.FIREFOX
caps["marionette"] = True
caps["binary"] = "/Applications/Firefox.app/Contents/MacOS/firefox-bin"

browser = Browser('firefox', capabilities=caps)
```

Code derived from: https://developer.mozilla.org/en-US/docs/Mozilla/QA/Marionette/WebDriver

**Comment by andrewsmedina** [comment]
A way to support Marionette by default is to create a driver that sets these capabilities by default.

**Comment by luzfcb** [comment]
after Selenium 3.0, Marionette (via geckodriver) is used by default. splinter Firefox driver not work if `geckodriver` is not in the `PATH`

i send a pull-request to update the docs: https://github.com/cobrateam/splinter/pull/521
