### ISSUE TITLE
Chrome WebDriver always starts in incognito mode

### ISSUE THREAD

**Issue by tomchuk** [cobrateam/splinter#506]
It seems https://github.com/cobrateam/splinter/commit/89a572313ff59bf0d491ad68142a10151185ac5c added a bit of a logic error: `incognito=False` as a default arg, followed by `incognito is not None`, results in the webdriver being instantiated in incognito mode unless `incognito` is explicitly set to `None`. PR incoming...

**Comment by andrewsmedina** [comment]
This was fixed in the latest version
