### ISSUE TITLE
status_code is only ever 200 - OK.

### ISSUE THREAD

**Issue by lexual** [cobrateam/splinter#509]
See attached testcase.

A status_code of 200 seems to be hard-coded since this commit?

https://github.com/cobrateam/splinter/commit/d151c565c1068c6f0ac3f09ff010353b9b1a9de2

```
import splinter

with splinter.Browser('firefox') as browser:
    # should be 200
    browser.visit('http://google.com')
    print(browser.status_code.code)
    print(browser.status_code.is_success())

    browser.visit('http://google.com/is_this_a_bug')
    print(browser.status_code.code)
    print(browser.status_code.is_success())

    browser.visit('http://github.com/is_this_a_bug/is_this_a_bug_project')
    print(browser.status_code.code)
    print(browser.status_code.is_success())

    browser.visit('http://this_domain_doesnt_even_exist.coma')
    print(browser.status_code.code)
    print(browser.status_code.is_success())
```

Gives this output:

```
$ python ./testcase.py 
200
True
200
True
200
True
200
True
```

This should be returning 404 for all but the 1st example.

**Comment by bmcculley** [comment]
Not sure if it's an acceptable fix, but I just created a PR #510 which uses httplib to address this bug. It makes another request for the HEAD of the page and returns the status code and reason.

The example test case above now returns:

```
$ python testcase.py
301
True
404
False
301
True
301
True
```

**Comment by bmcculley** [comment]
Sorry, I didn't really look at the old removed code before doing this. That was a much better implementation but pretty much the same thing.

What about running splinter with a proxy server by default that would deliver the status code without needing to make another request?

**Comment by andrewsmedina** [comment]
How this proxy server will work?

**Comment by bmcculley** [comment]
So, I think it would require quite a bit of rewriting splinter to get it to work, firefox I believe needs to use the hub server in order to get it to work with a proxy. Chrome and phantomjs can be set fairly easily, not sure about the others though.

I was thinking it would be possible to run the proxy as a subprocess and pass the http status code back to splinter. I'm thinking it could use openssl to handle secure connections. I'm not sure if something like this would be acceptable to add to the project since it would require so much refactoring, more overhead, and extra components to make it all work.

**Comment by samuelcolvin** [comment]
Do we have an update on when this is going to be fixed? 

For me this is about the most serious issue imaginable with splinter: the primary test of server response is incorrect such that tests are likely to pass when they should fail! 

:ghost: :scream: :imp: :hankey: :bug: :japanese_ogre: :no_good:

**Comment by andrewsmedina** [comment]
this bug is serious, but there is no easy way to fix it for the drivers based on selenium webdriver. 

a way is to duplicate the requests, we can do it only if the status_code is called.

I believe that this way can be a good way until we find a better way

**Comment by MrOerni** [comment]
Same here 

```
Python 3.5.2 (default, Oct 18 2016, 14:59:04) 
[GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.38)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from splinter import Browser
>>> b = Browser('chrome')
>>> b.visit('http://this_cant_be_rightabfql4ith3tuugerg.asdfubilh')
>>> b.status_code.code
200
>>> 
```

What is going on? If this doesn't work splinter will be a no go in no time.

**Comment by samuelcolvin** [comment]
**Bump**

Is anything happening here? 

This is a pretty serious error since it's not being fixed can we assume spinter is abandoned?

**Comment by samuelcolvin** [comment]
Wow, ok development seems to be continuing while this error is ignored.

If this is very difficult to fix, can I suggest splint just raises `NotImplementedError` on access to `status_code` so at least people don't assume it's working?

**Comment by andrewsmedina** [comment]
Splinter is not abandoned. But there is no easy way to fix it.  

Raises `NotImplementedError` for selenium drivers can be a way. Or another ways is to duplicate the requests if the status_code is called.

**Comment by samuelcolvin** [comment]
Multiple requests is difficult, `POST` requests are likely to not be idempotent, eg. the status code of a `POST /create/user` request the second time is very likely to be different to the first request. Even multiple `GET` requests could have effects so duplicating them probably does more harm than goodup.

Leave duplicated requests up to the application developer.

If there really isn't a reliable way of getting the status code from the main request, I think `NotImplementedError` is the only sensible solution.

**Comment by ncoghlan** [comment]
Someone mentioned this bug to me and I was puzzled as to why I hadn't noticed it myself, and then realised it was because of the way I had structured my test cases: all my status code tests just use plain requests calls, without invoking splinter at all. I then only use splinter for interaction tests in the 200 OK case.

So +1 from me for having `status_code` raise `NotImplementedError("Selenium WebDriver does not report HTTP status codes")` (or some other appropriate message) in cases where the driver can't set it reliably.

**Comment by andrewsmedina** [comment]
I'm +1 for `status_code` raise `NotImplementedError` in webdriver.

**Comment by andrewsmedina** [comment]
after the https://github.com/cobrateam/splinter/commit/2e5135460610149a1082b2aaca61fffc10beae40 in `0.8` the drivers based on webdriver will `raise NotImplementedError` in `status_code`
