### ISSUE TITLE
TCP Socket reuse problem in chrome driver

### ISSUE THREAD

**Issue by HoverWANG** [cobrateam/splinter#516]
It seems that every time I request to chrome driver, system will generate a [system process] with PID=0, state = TIME_WAIT, after a short while all my local ports are occupied and the system report WinError 10048: 'Only one usage of each socket address is normally permitted'

Do anyone know how to fix it? Thanks!

I have tried to set: 
s.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)

**Comment by andrewsmedina** [comment]
@HoverWANG what version of splinter and chrome driver are you using?

**Comment by HoverWANG** [comment]
@andrewsmedina I am using the latest version: Splinter 0.7.4 and chrome driver 2.24.

**Comment by rmeyer17** [comment]
@andrewsmedina are you still having this issue/have you found resolution?  I recently ran into the same problem using Splinter 0.7.5 & Chromedriver 2.30..

**Comment by jsfehler** [comment]
This doesn't appear to be an issue with splinter.
