### ISSUE TITLE
how to access element in iframe that has no tag

### ISSUE THREAD

**Issue by aswwindkk** [cobrateam/splinter#520]
i'd like to try the way ----with browser.get_iframe("**") as iframe:
but the iframe doesn't has a tag of id or name even index,how could i access the element in this kind of frame
 i want to click the date 20160925,the source code is something like this:
![qq 20161020154544](https://cloud.githubusercontent.com/assets/22768303/19550593/c17564c2-96dc-11e6-8a01-115e22d24dcb.png)
thanks

**Comment by andrewsmedina** [comment]
closed in 0.11.0 release
