### ISSUE TITLE
Example script: OSError: [Errno 20] Not a directory

### ISSUE THREAD

**Issue by karellat** [cobrateam/splinter#526]
Hi all, 
I tried to run example script from the very bottom of this  [site:](https://splinter.readthedocs.io/en/latest/tutorial.html.) 
I get following error message. (firefox installed)

> Traceback (most recent call last):
>   File "hello.py", line 3, in <module>
>     browser = Browser()
>   File "/usr/local/lib/python2.7/dist-packages/splinter/browser.py", line 63, in Browser
>     return driver(*args, **kwargs)
>   File "/usr/local/lib/python2.7/dist-packages/splinter/driver/webdriver/firefox.py", line 48, in __init__
>     timeout=timeout)
>   File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/firefox/webdriver.py", line 135, in __init__
>     self.service.start()
>   File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/common/service.py", line 64, in start
>     stdout=self.log_file, stderr=self.log_file)
>   File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
>     errread, errwrite)
>   File "/usr/lib/python2.7/subprocess.py", line 1327, in _execute_child
>     raise child_exception
> OSError: [Errno 20] Not a directory

**Comment by andrewsmedina** [comment]
to run the example, `firefox` should be installed. there are more info here: http://splinter.readthedocs.io/en/latest/drivers/firefox.html#module-splinter.driver.webdriver.firefox
