### ISSUE TITLE
How to handle the window.alter() event when I use the splinter?

### ISSUE THREAD

**Issue by Beloce** [cobrateam/splinter#530]
As the title says.
I can not find any information from google or  API docs about this issue.

Thanks a lot.

**Comment by andrewsmedina** [comment]
Hi @Beloce, this doc page can help you? http://splinter.readthedocs.io/en/latest/iframes-and-alerts.html?highlight=alert#handling-alerts-and-prompts

**Comment by Beloce** [comment]
I was so careless.
Thanks a lot! @andrewsmedina

**Comment by andrewsmedina** [comment]
@Beloce can we close this issue?
