### ISSUE TITLE
__init__() got an unexpected keyword argument 'mech_browser'

### ISSUE THREAD

**Issue by rusq** [cobrateam/splinter#531]
Hi there,

Facing this when trying to facilitate `zope.browser` driver.

* Zope version: zope.testbrowser-5.1-py2.7-nspkg.pth
* Splinter version: splinter-0.7.5.dist-info
* Python version: 2.7.10
* uname: `Darwin Kernel Version 15.6.0: Mon Jan  9 23:07:29 PST 2017; root:xnu-3248.60.11.2.1~1/RELEASE_X86_64`

~~~python
>>> from splinter import Browser
>>> b = Browser('zope.testbrowser')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/rustam/.virtualenvs/python2/lib/python2.7/site-packages/splinter/browser.py", line 63, in Browser
    return driver(*args, **kwargs)
  File "/Users/rustam/.virtualenvs/python2/lib/python2.7/site-packages/splinter/driver/zopetestbrowser.py", line 71, in __init__
    self._browser = Browser(mech_browser=mech_browser)
TypeError: __init__() got an unexpected keyword argument 'mech_browser'
~~~

Please let me know if any additional details required.

**Comment by damienrj** [comment]
I am also having the same problem. Did you figure it out?

**Comment by hltbra** [comment]
It looks like the interface used by Splinter was changed a long time ago but nobody noticed.

See these commits:

* https://github.com/zopefoundation/zope.testbrowser/commit/d383c611944289b2627c8ce17d82e77abf006281#diff-23a3cf799e53e2b29e5fcf8b02c23ea4L186
* https://github.com/zopefoundation/zope.testbrowser/commit/b48d53ba605f8c16b2cb0409a860df8b349eb3e6


@rusq, @damienrj: If you want to make it work without changing splinter, try downgrading zope.testbrowser to version 4.0.2 or older.

The right fix is to change splinter to work with the "new" interface, though.

**Comment by andrewsmedina** [comment]
After 0.9.0 the zope testbrowser 5+ is supported
