### ISSUE TITLE
Expected browser binary location, but unable to find binary in default location

### ISSUE THREAD

**Issue by trahloff** [cobrateam/splinter#532]
With the Dockerfile:
```
FROM python:2.7-onbuild

RUN cd /usr/src/app
RUN mkdir /usr/src/app/drivers
RUN wget https://github.com/mozilla/geckodriver/releases/download/v0.14.0/geckodriver-v0.14.0-linux32.tar.gz
RUN tar xzf geckodriver-v0.14.0-linux32.tar.gz -C /usr/src/app/drivers
env PATH /usr/src/app/drivers:$PATH

CMD [ "python", "./app.py" ]
```

I get the error:
`selenium.common.exceptions.WebDriverException: Message: Expected browser binary location, but unable to find binary in default location, no 'moz:firefoxOptions.binary' capability provided, and no binary flag set on the command line`

The geckodriver is downloaded and added to tha PATH. When I try this on a native Win10 machine (w/o Docker) the app.py works. 

Are there some undocumented dependencies?

**Comment by 1pyxa1** [comment]
@trahloff hi, did you install Firefox to the image?

**Comment by jsfehler** [comment]
Seems like this is only an issue with Firefox not being installed to the image. Closing.
