### ISSUE TITLE
Support for NightmareJS

### ISSUE THREAD

**Issue by dan-passaro** [cobrateam/splinter#536]
NightmareJS is a new alternative to PhantomJS, that uses Electron under the hood. See: https://github.com/segmentio/nightmare

I think it would be great to add support for this to splinter.

Curious if any work has been done on this yet, or if there's any interest in merging a PR that provided it. Since Selenium provides the PhantomJS support it seems like waiting for Selenium to implement NightmareJS support is the easiest path forward. But it might be more reliable to provide support for NightmareJS directly within splinter.

**Comment by jsfehler** [comment]
NightmareJS is dead: https://github.com/segmentio/nightmare/issues/1616
