### ISSUE TITLE
Pass chromedriver chrome_options args set user profile

### ISSUE THREAD

**Issue by RJTabassi** [cobrateam/splinter#540]
I am desperately trying to set the user to default and drive the browser, with this code, I can set the user, but not driver the browser further.

from selenium.webdriver import Chrome
from selenium.webdriver.chrome.options import Options
from splinter.driver.webdriver import BaseWebDriver, WebDriverElement

options = Options()
options.add_argument('--user-data-dir=C:\\Users\\<username redacted>\\AppData\\Local\\Google\\Chrome\\User Data\\Default')
browser = BaseWebDriver()
browser.driver = Chrome(chrome_options=options)
browser.visit('https://www.google.com')

I have been attempting to utilize stackoverflow and read the docs, it seems I should be able to do something like this, but it's not loading the profile

from splinter import Browser
from selenium import webdriver
options = webdriver.ChromeOptions()
options.add_argument('--user-data-dir=C:\\Users\\<username redacted>\\AppData\\Local\\Google\\Chrome\\User Data\\Default')
browser = Browser('chrome', options)
browser.visit('mysite')
browser.find_by_xpath('//*[@id="Login"]').click()

or this

from selenium import webdriver
from splinter import Browser

chrome_options = webdriver.ChromeOptions()
chrome_options.add_argument("args",
                                       '--user-data-dir=C:\\Users\\<username redacted>\\AppData\\Local\\Google\\Chrome\\User Data\\Default')
browser = Browser('chrome', options=chrome_options)

**Comment by me21** [comment]
```
from selenium import webdriver
options = webdriver.ChromeOptions()
options.add_argument('--user-data-dir=C:\Users\\AppData\Local\Google\Chrome\User Data')
```

Do not pass "Default" at the end of user data dir.
