### ISSUE TITLE
Session ID with Remote Webdriver

### ISSUE THREAD

**Issue by cjvanderlinden** [cobrateam/splinter#549]
I may just not be thinking about this right, but I am trying to access the session id from a remote webdriver via Splinter.  Specifically, I want to create a session on a selenium grid, do stuff, wait a few minutes, then do some more stuff, etc.  

I am not sure how I would go about using splinter, but being able to create a new python object that refers to the still active browser session via an id (vs pickling the splinter object currently).

**Comment by pouledodue** [comment]
@cjvanderlinden did you find a way to use sessions

**Comment by jsfehler** [comment]
Closing, since this sounds more like a Selenium issue than a Splinter issue. The session ID of a remote WebDriver instance can be retrieved using Selenium's API.
