### ISSUE TITLE
New Release

### ISSUE THREAD

**Issue by href** [cobrateam/splinter#550]
I noticed that there hasn't been a release in a while, even though there's some great new features queued up in the commit-log. Any chance of getting a new release?

**Comment by andrewsmedina** [comment]
@href, I will try to make a release in this week.

**Comment by href** [comment]
Thanks :)

**Comment by andrewsmedina** [comment]
0.7.6 released: https://splinter.readthedocs.io/en/latest/news/0.7.6.html
