### ISSUE TITLE
Chrome --disable-gpu flag

### ISSUE THREAD

**Issue by miohtama** [cobrateam/splinter#554]
Currently running a headless Chrome tests on a server, including TravisCI servers, require passing `--disable-gpu` to `chrome` process.  Otherwise you get error "exit code 1" from Selenium. As far as I know there is no published schedule when `--disable-gpu` goes away as promised by Chrome development team.

I suggest adding a flag to `chrome_options` to control this besides `--headless`. 

I can champion a PR to get this added.

Example where this should be added:

https://github.com/websauna/splinter/commit/607ab7c4386a3f5d4edc3f3d96aa42aa94def812

**Comment by andrewsmedina** [comment]
Hi @miohtama can you add a PR with this change?
