### ISSUE TITLE
Chrome headless not redirecting

### ISSUE THREAD

**Issue by ghost** [cobrateam/splinter#558]
I have told chrome headless to visit a page which issues a redirect, but the redirect is never happening. It just sits on the page... Is there some special command that I need to tell it to follow the redirect chain down?

**Comment by hyrumwhite** [comment]
I too am experiencing this issue.

**Comment by pouledodue** [comment]
me too

**Comment by rmeyer1** [comment]
![fail-test_132_c2_dzaf2e](https://user-images.githubusercontent.com/30154846/32807660-9a4ff596-c95e-11e7-91a7-460dee633864.png)
I am also experiencing a similar glitch when trying to run chrome headless using the splinter browser variable.  

For example, here is the code I use before a scenario is run to initialize the browser:
`def before_scenario(context, scenario):
    serv_args = [ "--ignore-ssl-errors=yes"]
    #chrome or phantomjs, set in environment variables
    logging.info("RUNNING: " + scenario.name)
    print("Browser Test starting.\n")
    if os.environ['browser'] == 'firefox':
        context.browser = Browser(os.environ['browser'])
    elif os.environ['browser'] == 'chrome':
        context.browser = Browser(os.environ['browser'], service_args=serv_args)
    else:
        context.browser = Browser(os.environ['browser'], service_args=serv_args)` 

When I do not include the headless=True tag the page redirects fine

![image](https://user-images.githubusercontent.com/30154846/32807410-bf7de9e6-c95d-11e7-8585-a2b341f5b9fe.png)

As soon as I include the headless=True argument in my browser setup Chrome is unable to redirect and it the screenshot is just a plain white screen. 
`def before_scenario(context, scenario):
    serv_args = [ "--ignore-ssl-errors=yes"]
    #chrome or phantomjs, set in environment variables
    logging.info("RUNNING: " + scenario.name)
    print("Browser Test starting.\n")
    if os.environ['browser'] == 'firefox':
        context.browser = Browser(os.environ['browser'])
    elif os.environ['browser'] == 'chrome':
        context.browser = Browser(os.environ['browser'], headless=True,service_args=serv_args)
    else:
        context.browser = Browser(os.environ['browser'], service_args=serv_args)`

**Comment by itereshchuk** [comment]
same for selenium and chrome webdriver

**Comment by lowe0506** [comment]
I have the same issue too

**Comment by itereshchuk** [comment]
https://bugs.chromium.org/p/chromedriver/issues/detail?id=2440#c2

**Comment by GuptaMegha** [comment]
I used a workaround to change the user-agent:
chromeOptions.addArguments("--user-agent=Chrome/77");
This solved my issue, for now!

**Comment by f4br3** [comment]
> I used a workaround to change the user-agent:
> chromeOptions.addArguments("--user-agent=Chrome/77");
> This solved my issue, for now!

It works, huge thanks!

**Comment by jsfehler** [comment]
Closing, since this is a chromedriver issue and not a splinter issue.
