### ISSUE TITLE
Make changelog browsable

### ISSUE THREAD

**Issue by miohtama** [cobrateam/splinter#560]
Currently Splinter changelog is available in the Sphinx documentation https://github.com/cobrateam/splinter/tree/master/docs/news

However the changelog is not available in the sidebar http://splinter.readthedocs.io/en/latest/ or easily user discoverable.

I recommend adding a Changelog page in the documentation that indexes all individual changelog entries, making them available easily in Sphinx user browsable documentation.

If you have nothing against this I can make a PR.

**Comment by miohtama** [comment]
Furthermore I suggest enforcing a policy that all PRs need to include a corresponding changelog entry.

**Comment by andrewsmedina** [comment]
@miohtama great idea. Can you send a pr?

**Comment by damon-myers** [comment]
Hi @andrewsmedina, would you still be interested in a PR for this?

**Comment by jsfehler** [comment]
Fixed by #781
