### ISSUE TITLE
Suggest add in docs the possibility to use selenium special Keys

### ISSUE THREAD

**Issue by XuanShine** [cobrateam/splinter#567]
I'm new on using github tools.
We should add in the docs that we can use selenium special Keys:

e.g. (return key):
from selenium.webdriver.common.keys import Keys
ElementAPI.type(Keys.RETURN)

or add a reference to selenium docs for special keys

**Comment by andrewsmedina** [comment]
+1

**Comment by caoliang12121** [comment]
yes,yes,yes!!

**Comment by ynx0** [comment]
I would like to help update the docs. Can I start working on this?

**Comment by andrewsmedina** [comment]
@ynx0 yes. Fell free to contribute with this issue.

**Comment by tetsucceed** [comment]
Hello, this is my first time trying to contribute to Open Source. So if this issue is still open i think it's good chance to start with this.

**Comment by andrewsmedina** [comment]
@tetsucceed this issue is still open. So, fell free to work on it. If you nedd help, let us know.

**Comment by jsfehler** [comment]
Fixed by #722
