### ISSUE TITLE
Firefox now support headless mode with environ variable

### ISSUE THREAD

**Issue by Benoss** [cobrateam/splinter#568]
Firefox support headless mode by setting MOZ_HEADLESS environ variable 

This code is showing how to do it at the moment (Tested with firefox 57 on windows)
```
import os
os.environ['MOZ_HEADLESS'] = '1'

with Timer(prefix="create browser"):
    browser = Browser('firefox')

with Timer(prefix="go to url"):
    url = "https://google.com"
    browser.visit(url)
```

maybe simply add Browser('firefox', headless=True) to set the environment variable?

reference: https://intoli.com/blog/running-selenium-with-headless-firefox/

**Comment by andrewsmedina** [comment]
Hi @Benoss this feature was added by https://github.com/cobrateam/splinter/pull/561

I will make a new release with this new feature

**Comment by haroldrandom** [comment]
Hope Release version coming soon.
`pip install splinter` still refer to the old version 0.7.6

**Comment by andrewsmedina** [comment]
released https://splinter.readthedocs.io/en/latest/news/0.7.7.html

**Comment by haroldrandom** [comment]
Great! Thx for the effort!

**Comment by jgeorgeson** [comment]
I'm trying to follow the quick tutorial and I it's launching the full firefox GUI and it never gets past the `Browser()` call. I tried the `headless=True` that @haroldrandom mentioned and also the `MOZ_HEADLESS` variable like in the initial issue description here and neither works. I have v0.7.7 installed, have tried with both Python 2.7.5 and Python 3.6.3 (the versions packaged in CentOS/EPEL 7).

**Comment by jgeorgeson** [comment]
This may due to installed firefox version. Looks like headless requires v55 and CentOS 7 only has 52.
