### ISSUE TITLE
Question: Execution of "sessionStorage.access_token" return NoneType

### ISSUE THREAD

**Issue by sachs7** [cobrateam/splinter#569]
from splinter import Browser
b = Browser('chrome')
v = b.execute_script("return sessionStorage.access_token")
""" Note: access_token is a key """
print(v) --> empty
type(v) --> NoneType

Need help on how to access sessionStorage contents?

**Comment by andrewsmedina** [comment]
@sachs7 splinter has two methods to interact with javascript: `execute_script` and `evaluate_script`. For scripts that return values, you should use `evaluate_script`.

And to get a sessionStorage key you should use getItem method:

```
v = b.evaluate_script("sessionStorage.getItem('access_token');")
```

**Comment by sachs7** [comment]
Thanks, @andrewsmedina. Will give it a try.

**Comment by sachs7** [comment]
Works! Thanks @andrewsmedina 

Closing this ticket.
