### ISSUE TITLE
cannot interact with element

### ISSUE THREAD

**Issue by Zawadidone** [cobrateam/splinter#574]
selenium.common.exceptions.InvalidElementStateException: Message: {"errorMessage":"Element is not currently interactable and may not be manipulated","request":{"headers":{"Accept":"application/json","Accept-Encoding":"identity","Connection":"close","Content-Length":"81","Content-Type":"application/json;charset=UTF-8","Host":"127.0.0.1:49599","User-Agent":"Python http auth"},"httpVersion":"1.1","method":"POST","post":"{\"sessionId\": \"489ea4a0-eaeb-11e7-b578-f52101328173\", \"id\": \":wdc:1514368193436\"}","url":"/clear","urlParsed":{"anchor":"","query":"","file":"clear","directory":"/","path":"/clear","relative":"/clear","port":"","host":"","password":"","user":"","userInfo":"","authority":"","protocol":"","source":"/clear","queryKey":{},"chunks":["clear"]},"urlOriginal":"/session/489ea4a0-eaeb-11e7-b578-f52101328173/element/:wdc:1514368193436/clear"}}
Screenshot: available via screen

**Comment by andrewsmedina** [comment]
@Zawadidone what driver are you using?

**Comment by Zawadidone** [comment]
phantomjs 
phantomjs-2.1.1-windows

**Comment by Zawadidone** [comment]
And also on linux
