### ISSUE TITLE
Killing Python process doesn't kill geckodriver

### ISSUE THREAD

**Issue by to175** [cobrateam/splinter#582]
Hi,

When I stop the Python script (by killing the kernel or closing Python) it doesn't kill geckodriver and firefox, so it floods my memory...

Do you also have had this issue ? How to fix it please ?

**EDIT : i have noticed that the geckodrive (and firefox) is not closed at all even when the Python script finish normally !**

**EDIT 2 : nothing better when I add browser.quit() !** :(

**Comment by jsfehler** [comment]
This doesn't appear to be an issue with splinter.
