### ISSUE TITLE
webdriver execute_script discards result

### ISSUE THREAD

**Issue by jaraco** [cobrateam/splinter#584]
The [current implementation of execute_script](https://github.com/cobrateam/splinter/blob/c2f65f47ad0ff3a630f3bd4dbc1d0000a99f4412/splinter/driver/webdriver/__init__.py#L197) discards the result from `driver.execute_script`. Instead, it should pass through the result.

**Comment by jaraco** [comment]
Aha. I think perhaps it's by design that `execute_script` returns nothing, because `evaluate_script` will return the result of a single expression. But this approach is limiting and confusing. It's confusing because various resources for webdriver suggest using `execute_script("return ...")`. It's limiting because the webdriver allows `execute_script("statement1; statement2; return val;")`, whereas splinter doesn't provide any such interface.

Is there any reason that `execute_script` shouldn't simply return its result also?

**Comment by andrewsmedina** [comment]
I believe that we can add the return in `execute_script` and deprecated the `evaluate_script` in the future
