### ISSUE TITLE
_element should become part of the official API (allows Selenium calls)

### ISSUE THREAD

**Issue by samboy** [cobrateam/splinter#591]
Let's look at some code similar to something I write using Splinter:

```
a = browser.find_by_id("foo")
txt = a._element.get_attribute('outerHTML')
try:
   txt.find('some HTML')
except:
   print("Test FAIL")
   return -1
```

The point being, I'm using _element to access a method in the underlying Selenium that Splinter does not appear to support.

We should make this part of the official API: If you want to do something with an element and Splinter does not support it, use _element to make the required Selenium call. This way, already written code does not need to be revised.

**Comment by andrewsmedina** [comment]
In the @samboy case it is possible to access the `element` attributes:

```
txt = a['outerHTML']
```

In @youtux case I believe that we should solve this add a `execute_script` by `element`

What do you guys think about it?

**Comment by samboy** [comment]
The question I have is this: Is there a commitment from the Splinter development team to make sure `_element` will continue to work in the future, or is it possible Splinter team one day decide to break this undocumented feature?

**Comment by andrewsmedina** [comment]
There is no plan to remove the `_element` for selenium based drivers. But If the community embrace the idea we can follow a path to make this official. Making a way to officially expose the `driver` element.

**Comment by youtux** [comment]
I see that https://github.com/cobrateam/splinter/commit/1f2bc75cda956ab9c4063ed7ede8521d7c32a4d7 help with my use case, in the sense that I don't have to use the private `_driver` property. Can you release a new version of splinter so that I can take advantage of `scroll_to()`?

**Comment by andrewsmedina** [comment]
@youtux we should add this in 0.10 with some bug fixes.
