### ISSUE TITLE
DeprecationWarning: use options instead of chrome_options

### ISSUE THREAD

**Issue by strichter** [cobrateam/splinter#599]
There is a deprecation warning that gets raised every time the Chrome backend is used. 

This is because `splinter/driver/webdriver/chrome.py` (line 35) uses `chrome_options` instead of `options`. It is literally a 7 character fix to use `options` instead, since this is what the underlying selenium code does.

**Comment by strichter** [comment]
Seems to be resolved in master. When will there be a new release?

**Comment by andrewsmedina** [comment]
0.8 will be released soon. In this or the next week

**Comment by strichter** [comment]
@andrewsmedina Thanks for the update. (There are other goodies in master that seem useful.)
