### ISSUE TITLE
Is It Time for a New Stable Release?

### ISSUE THREAD

**Issue by StabbarN** [cobrateam/splinter#600]
I'm happy to see a roadmap for 1.0 (#597) but I'm also longing for a stable release with version 0.8.0 or 0.7.7. 29 commits in master since 0.7.6.

**Comment by andrewsmedina** [comment]
Hi @StabbarN 0.8 will be released soon. In this or the next week

**Comment by StabbarN** [comment]
Thanks for releasing 0.8.0!
