### ISSUE TITLE
Headless mode in remote webdriver

### ISSUE THREAD

**Issue by j7an** [cobrateam/splinter#602]
Not sure if its possible, but it would be great if we can look into getting headless mode working via remote webdriver.

Referencing discussion on https://github.com/cobrateam/splinter/issues/597#issuecomment-377111031

**Comment by jsfehler** [comment]
@andrewsmedina Remote Webdriver already supports a headless mode by supplying an Options object with the correct parameters. I don't see a benefit to adding more arguments to the Remote class.

Instead, it would be better to implement a standardized Options object for splinter's webdrivers. The parsing of the browser name and handling the logic will be cleaner that way.
