### ISSUE TITLE
Action Chains in Remote Webdriver

### ISSUE THREAD

**Issue by j7an** [cobrateam/splinter#603]
Currently when trying to use action chains (e.g. mouse actions) with remote webdriver, I get an error that it is not supported (e.g. Firefox). I have verified if I use Selenium API directly with remote webdriver for action chains the mouse actions work.

We should look into getting this resolved.

Referencing discussion here https://github.com/cobrateam/splinter/issues/597#issuecomment-377111031

**Comment by jsfehler** [comment]
@andrewsmedina I believe this issue has been fixed in 0.12.0
