### ISSUE TITLE
Support Django 2.0 test client as backend

### ISSUE THREAD

**Issue by Incanus3** [cobrateam/splinter#605]
Hi,
we've recently migrated to Django 2.0. Now I wanted to create a high-level test using splinter with django backend, but found out, that I can't even install splinter[django], since it depends on django<1.12. Is there something I can do to support Django 2.0?

**Comment by andrewsmedina** [comment]
We should add the support for Django 2.0

**Comment by andrewsmedina** [comment]
closed by #615
