### ISSUE TITLE
Chrome --no-sandbox flag

### ISSUE THREAD

**Issue by eggnita** [cobrateam/splinter#606]
It seems that in the latest versions of Chrome you cannot start without --no-sandbox flag in environments like Docker. This issue appears in other common CI tools like travis (which already got an updated  chrome version in the build environment images)
You can see more details [here](https://github.com/karma-runner/karma-chrome-launcher/issues/158) 
I can PR this if needed.
The place where this option should be added is:
[eggnita/splinter@d54fecf](https://github.com/eggnita/splinter/blob/d54fecf7ca95b3eb6814aad0eae14a5e44ef7591/splinter/driver/webdriver/chrome.py#L34)

This can also be fixed by handling #345

**Comment by andrewsmedina** [comment]
I believe that we should merge #345

**Comment by eggnita** [comment]
@andrewsmedina can I help with the merge? or do you have any idea when that can be merged? Because it seems that the removal of the headless param and the addition of the chrome_options will introduce some breaking changes. What are your thoughts regarding this?

**Comment by andrewsmedina** [comment]
The PR #345 needs tests. I would be nice if you can help adding tests for this pr.
