### ISSUE TITLE
splinter 0.8.0 throws NotImplementedError for browser.status_code.code

### ISSUE THREAD

**Issue by smhall05** [cobrateam/splinter#609]
splinter version 0.8.0
python version 2.7.6

When using a check for 200 on a successful page access:

> if browser.status_code.code == 200:

 I am seeing, this worked in version 0.7.7:

> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "/usr/local/lib/python2.7/dist-packages/splinter/driver/webdriver/__init__.py", line 182, in status_code
>     raise NotImplementedError
> NotImplementedError

Repro steps:

`
ubuntu@ip-xxxxxxx:~$ python
Python 2.7.6 (default, Oct 26 2016, 20:30:19) 
[GCC 4.8.4] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from splinter import Browser
>>> browser = Browser('firefox')
>>> browser.driver.set_window_size(640, 480)
>>> browser.visit("http://www.google.com")
>>> browser.status_code.code
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/splinter/driver/webdriver/__init__.py", line 182, in status_code
    raise NotImplementedError
**NotImplementedError**
>>> browser.status_code
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/splinter/driver/webdriver/__init__.py", line 182, in status_code
    raise NotImplementedError
**NotImplementedError**
`

**Comment by andrewsmedina** [comment]
hi @smhall05 this is not a bug this is a behaviour.

some drivers does not return the status code after `visit` a page. Before 0.8.0 the splinter always returned `200` in these cases. But this is a false positive.

In 0.8.0 we changed this behaviour. Instead to do a fake return splinter raises the proper error showing that this feature was not implemented.

**Comment by smhall05** [comment]
@andrewsmedina What is the best way then to confirm I have accessed a page successfully?
