### ISSUE TITLE
javascript:void(0) - issue to click on menu

### ISSUE THREAD

**Issue by yannlm1** [cobrateam/splinter#610]
Splinter version 0.7.7
Python version 2.7.5

Hello All,

I'm struggling for clicking on this menu as below:

`<a class="buttons" id="STR_TOPNAV_REMOTE_CONTROL" href="javascript:void(0)" lnavobj="RMCNTRL_LEFTNAV">Remote Control</a>`

I also tried by class, Xpath, by ID with no luck, would you have any suggestion?

Thanks

**Comment by andrewsmedina** [comment]
@yannlm1 what driver are you using and how are you trying? I believe that `browser.find_by_id("STR_TOPNAV_REMOTE_CONTROL").click()" should works.

**Comment by yannlm1** [comment]
Hello,

I'm using geckodriver 0.20.0, with firefox version 59.0.2, I also tried by id, but didn't find the element as below:

```
Traceback (most recent call last):
  File "./kvm.py", line 24, in <module>
    browser.find_by_id("STR_TOPNAV_REMOTE_CONTROL").first.click()
  File "/usr/lib/python2.7/site-packages/splinter/element_list.py", line 53, in first
    return self[0]
  File "/usr/lib/python2.7/site-packages/splinter/element_list.py", line 44, in __getitem__
    self.find_by, self.query))
splinter.exceptions.ElementDoesNotExist: no elements could be found with id "STR_TOPNAV_REMOTE_CONTROL"
```

Here my code
```
#!/usr/bin/python
from splinter import Browser
import time
import getpass

pswd = getpass.getpass('Password:')

browser = Browser()
# Visit URL
url = "http://IP/page/login.html"

browser.visit(url)
browser.fill('T1', 'root')
browser.fill('T2', pswd)
browser.find_by_id("LOGIN_VALUE_1").first.click()
time.sleep(3)
browser.find_by_id("STR_TOPNAV_REMOTE_CONTROL").first.click()
```

**Comment by andrewsmedina** [comment]
In this example the use of `first` is not necessary. splinter aways will try to do an action in the first element if no one is specified. So you can replace `browser.find_by_id("LOGIN_VALUE_1").first.click()` by `browser.find_by_id("LOGIN_VALUE_1").click()`

**Comment by yannlm1** [comment]
Thanks,
So I tried with is_element_present
`browser.is_element_present_by_id("STR_TOPNAV_REMOTE_CONTROL", wait_time=10)`
I kept after
`browser.find_by_id("STR_TOPNAV_REMOTE_CONTROL").first.click()`

Result:
`splinter.exceptions.ElementDoesNotExist: no elements could be found with id "STR_TOPNAV_REMOTE_CONTROL"`

**Comment by andrewsmedina** [comment]
@yannlm1 are you sure that the `STR_TOPNAV_REMOTE_CONTROL` element is present after login?

**Comment by yannlm1** [comment]
As below, it's looks like, I need to put the focus (mouse) on the menu tab, and then it's highlighted.
How can I do this with splinter?
![remote control](https://user-images.githubusercontent.com/38974785/39765514-4c0d9614-52e2-11e8-9d8e-44bfe4380a49.png)

I tried to leave just browser.is_element_present_by_id("STR_TOPNAV_REMOTE_CONTROL", wait_time=10), and remove browser.find_by_id, I don't any output saying element is present.

Thanks.

**Comment by andrewsmedina** [comment]
You should use `get_iframe` to manipulated elements inside a frame: http://splinter.readthedocs.io/en/latest/iframes-and-alerts.html#using-iframes

**Comment by yannlm1** [comment]
Hello Andrew,

Could you please have a look to my question?

Thanks.

**Comment by andrewsmedina** [comment]
I don't know how to do it :(

**Comment by yannlm1** [comment]
In fact when I'm doing it with iframe, and I click on Open With (jviewer.jnlp), it's failing.
As below the logs from geckodriver:
`
INFO: >>> JWS: parsed jnlp after 99ms; jnlp=/tmp/mozilla_ylemouel0/jviewer-1.jnlp
INFO: extracted 2 native libs from Linux_x86_64.jar
INFO: >>> JWS: checked and (if necessary) deployed jars after 397ms: to directory /local/java.users/ylemouel/.java/deployment/cache/jws/jviewer-1__0.0.0; jnlp=/tmp/mozilla_ylemouel0/jviewer-1.jnlp
INFO: >>> JWS: launching with the following command line:
INFO: >>> JWS: /local/java.users/ylemouel/.java/deployment/cache/jws/jviewer-1__0.0.0/jviewer-1.jnlp_1_8.jws
INFO: >>> JWS: -cp
INFO: >>> JWS: /local/java.users/ylemouel/.java/deployment/cache/jws/jviewer-1__0.0.0/*
INFO: >>> JWS: -Djava.library.path=/local/java.users/ylemouel/.java/deployment/cache/jws/jviewer-1__0.0.0
INFO: >>> JWS:
INFO: >>> JWS: 10.8.160.113
INFO: >>> JWS: 7578
INFO: >>> JWS: K8bMfc2fMzupGFqT
INFO: >>> JWS: 0
INFO: >>> JWS: 0
INFO: >>> JWS: 0
INFO: >>> JWS: 5120
INFO: >>> JWS: 5123
INFO: >>> JWS: 255
INFO: >>> JWS: ":Ctrl+Alt+Del:Ctrl Alt Del:Alt+Tab:Alt Tab"
INFO: >>> JWS: EN
INFO: >>> JWS: YqJWxUSIiOQzPSSUzLV3m940KqQxIqos000
INFO: >>> JWS: ======== START OF APPLICATION LOGS ========
INFO: >>> JWS: launched process after 405ms: /tmp/mozilla_ylemouel0/jviewer-1.jnlp
INFO: >>> JWS: waiting max 60000ms for window to appear... /tmp/mozilla_ylemouel0/jviewer-1.jnlp
ERROR: Error: Could not find or load main class
`

Then I run manually from the tmp directory it works, so there is something wrong when using it via splinter click function.
`javaws /tmp/mozilla_ylemouel0/jviewer.jnlp`
