### ISSUE TITLE
element.find_by_text searches whole dom

### ISSUE THREAD

**Issue by jaraco** [cobrateam/splinter#612]
When trying to do a contextual search for text, the result returned includes all matching text for the whole DOM instead of just those nodes that are children of the contextual node.

**Comment by jaraco** [comment]
I believe the issue lies here https://github.com/cobrateam/splinter/blob/master/splinter/driver/webdriver/__init__.py#L407.

The `//*` means all nodes in dom. It should be `.//*` to mean all child nodes.

**Comment by andrewsmedina** [comment]
@jaraco this line is the `browser.find_by_text` and in this case the code is right. I believe that the bug is here in the `element.find_by_text`: https://github.com/cobrateam/splinter/blob/ed21fb5495965d265bd5bd3e95b0dfb7121da7c2/splinter/driver/webdriver/__init__.py#L618

**Comment by jaraco** [comment]
Yes. That makes sense.
