### ISSUE TITLE
How can i use select function without name?

### ISSUE THREAD

**Issue by chrisyangi** [cobrateam/splinter#620]
Below is the splinter docs 
        

def select(self, name, value):
        """
        Selects an ``<option>`` element in an ``<select>`` element using the ``name`` of the ``<select>`` and
        the ``value`` of the ``<option>``.

        Example:

            >>> browser.select("state", "NY")
        """
        raise NotImplementedError(
            "%s doesn't support selecting options in 'select' element." % self.driver_name)

Now i wanna know how can i use this function without 'name' where the 'select' only have  id and onclick() 

Thanks for your help!!!

**Comment by andrewsmedina** [comment]
You can find the `select` element by id, tag, css and them `select` the option:

```
element = browser.find_by_css('.mystate')
element.select('ny')
```

More refs here: https://splinter.readthedocs.io/en/latest/api/driver-and-element-api.html?highlight=select#splinter.driver.ElementAPI.select
