### ISSUE TITLE
“could not be scrolled into view”

### ISSUE THREAD

**Issue by TensorTom** [cobrateam/splinter#622]
I'm trying to automate logging into a web site using Splinter. There are a few selector methods I can use to click the login link but it doesn't matter. I always get:

`selenium.common.exceptions.ElementNotInteractableException: Message: Element <a class="tv-header__device-signin js-header__signin" href="#signin"> could not be scrolled into view`

Code:

```
from splinter import Browser

with Browser() as browser:
    browser.visit("https://www.tradingview.com")
    browser.click_link_by_href("#signin")
```

**Comment by ericminio** [comment]
In case it helps: I met this error message when the target had a size of zero

**Comment by bmcculley** [comment]
There are 2 links on the page with the href and text. So, you'll want to just find the elements first and then chose one to click on, here's the code that worked for me on that page.

```python
from splinter import Browser

with Browser() as browser:
    browser.visit("https://www.tradingview.com")
    signin_link = browser.find_by_text('Sign In')
    signin_link[1].click()
```

@andrewsmedina This isn't a bug with splinter, so I feel this issue can be closed.
