### ISSUE TITLE
Handle firefox closed by user

### ISSUE THREAD

**Issue by yannlm1** [cobrateam/splinter#630]
Dear Support,

I created a script based on splinter for sysadmin stuff (managing IPMI server web interface). 

My issue is that when a user close Firefox by clicking on exit (top right corner), I'd need to detect it on then send a browser.quit() . Is there way to do that, or another method?

Thanks for your help.

**Comment by yannlm1** [comment]
Dear Support,

Any help please?

Thanks.

**Comment by jsfehler** [comment]
This is more a selenium issue than a splinter issue, see: https://stackoverflow.com/questions/51685330/python-selenium-detect-when-the-browser-is-closed
