### ISSUE TITLE
Browser opens but no further actions

### ISSUE THREAD

**Issue by impshum** [cobrateam/splinter#632]
Just opens the browser and sits there with both Firefox and Chrome

Browsers - Firefox ESR & Chromium 68.0.3440.75

This is in the geckodriver.log

    [Child 2489] ###!!! ABORT: Aborting on channel error.: file /build/firefox-esr-TVuMhV/firefox-esr-52.9.0esr/ipc/glue/MessageChannel.cpp, line 2152

**Comment by impshum** [comment]
The latest. I just installed it.

**Comment by treyhunner** [comment]
I see the same behavior. I'm attempting to test with Firefox. If I stick in a breakpoint I can see that my actual test code doesn't even start executing.

**Comment by impshum** [comment]
@treyhunner Browser opens and..... nothing runs yes?

**Comment by treyhunner** [comment]
@impshum correct

**Comment by jsfehler** [comment]
This is a geckodriver issue, see the similar: https://github.com/mozilla/geckodriver/issues/285
