### ISSUE TITLE
Trying to run tests on windows environment leads to error "Failed to start test server: [Errno 2] No such file or directory: '/dev/null''

### ISSUE THREAD

**Issue by kolapsys** [cobrateam/splinter#648]
https://github.com/cobrateam/splinter/blob/69552e72ecf8c50c2ef34d9bfbc1baebc3db053d/run_tests.py#L61

In order to be able to run the tests cross-platform `"/dev/null"` should be replaced with `os.devnull`.

**Comment by kolapsys** [comment]
solution provided in PR #649

**Comment by andrewsmedina** [comment]
closed by #649
