### ISSUE TITLE
Remote Firefox doesn't support throws even if I use Chrome as remote

### ISSUE THREAD

**Issue by zeburek** [cobrateam/splinter#666]
As I see - there is problem in code, that doesn't verify what type of browser is used in remote.
So I would like to add a check of browser type - because if I re-write `element_type` with chromes `WebDriverElement` I have everything perfectly working.

**Comment by jsfehler** [comment]
Currently, the Chrome, Firefox, and Remove drivers all use the same WebDriverElement.

I'm closing this issue since it appears to be solved.
