### ISSUE TITLE
Django >= 2.0.6 now required for python > 3.3

### ISSUE THREAD

**Issue by theunraveler** [cobrateam/splinter#667]
[This commit](https://github.com/cobrateam/splinter/commit/907208296d1936b2e8abfe21b7109cb0dad9e6a2) ([this part in particular](https://github.com/cobrateam/splinter/commit/907208296d1936b2e8abfe21b7109cb0dad9e6a2#diff-2eeaed663bd0d25b7e608891384b7298R30)) pins the django version to >= 2.0.6 if you're installing on python 3.3. As far as I know, Django 1.11 is still supported on python 3, and this dependency declaration prevents me from using django 1.11 with splinter if I want to be on python 3.3.

I think the correct thing to do here is just to declare a dependency on `django >= 1.7.11` regardless of the python version, since this library supports all django versions above that, and has little to do with the python version.

**Comment by kierun** [comment]
Django 1.11 is a long term release and should be supported for as long as Django supports it.

Due to poetry dependency checks, I cannot run any of the behaviour tests I have. PITA.

**Comment by kierun** [comment]
Any update on this?
