### ISSUE TITLE
Chromeoptions does not work in new version

### ISSUE THREAD

**Issue by wurenbuxiao** [cobrateam/splinter#670]
Last day, I update my splinter and selenium and find out that it does not work when I pass chromeoptions to driver. Is it a bug or something? I did not change anything except updating my splinter and selenium to the newest version.

here is my test code:

from splinter import Browser
from selenium.webdriver.chrome.options import Options
chrome_options = Options()
chrome_options.add_argument("--user-data-dir=mypath")
driver = Browser('chrome',options=chrome_options)

**Comment by wurenbuxiao** [comment]
my path is C:\Users\Myname\AppData\Local\Google\Chrome\User Data

**Comment by andrewsmedina** [comment]
This code looks fine. What is the version of splinter and chromedriver?

**Comment by andrewsmedina** [comment]
@wurenbuxiao what is the chromedriver version? You can see the version using: `$ chromedriver --version`

**Comment by wurenbuxiao** [comment]
ChromeDriver 2.28.455520
Chrome 56.0.2924.87
