### ISSUE TITLE
How can I retrieve the cookies added post splinter driver instantiation

### ISSUE THREAD

**Issue by siddiqskm** [cobrateam/splinter#673]
I see that all the cookies available in the browser are collected at the instant of instantiating splinter browser object but say in case some of the cookies gets added while am using the driver is there any way to retrieve them? Does CookieManager perform any kind of refresh to retrieve the newly added ones?

Reference: https://github.com/cobrateam/splinter/blob/0aae2027b02635526e45e021d4a5f51a7f53613e/splinter/driver/webdriver/cookie_manager.py#L16

UseCase:
In case am using splinter for testing an application configured with any SAML provider like OKTA, the steps I need to follow are:
1) Instantiate splinter browser
2) Perform a visit and wait for the redirection to happen on SAML page
3) Key-In the right credentials on SAML login page
4) Successful Login

I observe that the cookies created post step 3 are available in browser but not retrieved via splinter cookies.all() call.

Can some one please help?

**Comment by jsfehler** [comment]
This sounds like a selenium and/or SAML and/or browser issue. I can't reproduce it using a trivial example.
