### ISSUE TITLE
headless=True is not working anymore

### ISSUE THREAD

**Issue by yannlm1** [cobrateam/splinter#677]
Dear Support,

Since two days, my script is working anymore with headless variable set to true, it's stuck before doing browser.visit(url)

As soon as I remove headless variable it works perfectly, could you please take a look ?

Thanks,

geckodriver version :  0.24.0
firefox : 65-2

**Comment by andrewsmedina** [comment]
The URL that you are using is public? Can you send this value to us to makes possible to reproduce this bug?

**Comment by yannlm1** [comment]
Hello

Not private, BMC board management for servers.

Thanks

Le 15 mars 2019 à 02:10, Andrews Medina <notifications@github.com<mailto:notifications@github.com>> a écrit :


The URL that you are using is public? Can you send this value to us to makes possible to reproduce this bug?

**Comment by mpasternak** [comment]
See my pull request, #768, this should fix that. @andrewsmedina , you around?

**Comment by andrewsmedina** [comment]
fixed by #768
