### ISSUE TITLE
WebDriverElement. select* implicitly rely on presence of name attribute for selector

### ISSUE THREAD

**Issue by aviskase** [cobrateam/splinter#681]
#620 asked about using `select` (and by extension, `select_by_text`) for an element without a name

But if you check implementation for methods defined for `WebDriverElement`, both contain search by selector's `name`

https://github.com/cobrateam/splinter/blob/32f11ff7fd7841b123f157720dcc95740f156ca8/splinter/driver/webdriver/__init__.py#L616

https://github.com/cobrateam/splinter/blob/32f11ff7fd7841b123f157720dcc95740f156ca8/splinter/driver/webdriver/__init__.py#L621

I want to make a pull request for fixing this behavior, but I'm not sure which would be better:
- completely remove `name` from xpath 
- use xpath with `name` if `self["name"]` is not empty, otherwise, use xpath without `name`

**Comment by andrewsmedina** [comment]
I believe that if the first approach is possible we can go with it.
