### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by jacebrowning** [cobrateam/splinter#695]
It's been 7 months since `0.10.0`. Could we get a new stable release?

**Comment by jacebrowning** [comment]
Specifically, I'm hitting this bug:

```
splinter/driver/webdriver/__init__.py:305: in get_alert
    return AlertElement(self.driver.switch_to.alert())
E   TypeError: 'Alert' object is not callable
```

which I can't trace to any code in `master` so I think might already be fixed.

**Comment by andrewsmedina** [comment]
We will make a release in this week.

**Comment by andrewsmedina** [comment]
0.11.0 released https://github.com/cobrateam/splinter/releases/tag/0.11.0
