### ISSUE TITLE
On some sites, the fill function does not work correctly

### ISSUE THREAD

**Issue by uasya1** [cobrateam/splinter#705]
On some sites, the fill function does not work correctly.
Characters are not fully entered.

Running in python venv (Win10x64) Python 3.6

Installed packages in venv:
splinter==0.10.0

from splinter import Browser

`.fill("123123")`
output:
`131
`
For example site http://npchk.nalog.ru/
`browser.find_by_xpath('//*[@id="inn"]').fill('5249155837')`

**Comment by jsfehler** [comment]
This site in particular is using some nasty javascript to validate the form value. This isn't something selenium or splinter can solve for you.
