### ISSUE TITLE
'extras_require' must be a dictionary Error while installing the new build in Mac OS 10.12.6

### ISSUE THREAD

**Issue by gkteck** [cobrateam/splinter#710]
The build is broken, getting the following error

error in splinter setup command: 'extras_require' must be a dictionary whose values are strings or lists of strings containing valid project/version requirement specifiers.

**Comment by jsfehler** [comment]
I can't reproduce this issue. This is probably an environment issue related to python, pip, and setuptools versions. Closing for now.
