### ISSUE TITLE
is_element_visible missing from API docs?

### ISSUE THREAD

**Issue by tony** [cobrateam/splinter#712]
[`is_element_visible`](https://github.com/cobrateam/splinter/blob/04a6da307f76d872ef1c227c47509fc983e5315c/splinter/driver/webdriver/__init__.py#L201) is a very helpful function, but haven't figured out why / what would be the clearest way to make it available in the docs (Should we make all `Window` available?)

**Comment by andrewsmedina** [comment]
A good place for the docs about this method is the `matchers` page: https://github.com/cobrateam/splinter/blob/master/docs/matchers.rst

**Comment by sukhbeersingh** [comment]
Hi , I would like to work on this issue.

**Comment by andrewsmedina** [comment]
@sukhbeersingh fell free to work on it. If you need help let us know.

**Comment by sukhbeersingh** [comment]
Is the intent to just include the said function in the matchers page? Or is it to make a new page (windows.rst) and incorporate this in there?

**Comment by andrewsmedina** [comment]
closed by #723
