### ISSUE TITLE
How To Access Selenium Webdriver Through Splinter in Python

### ISSUE THREAD

**Issue by JeffreyWinger55** [cobrateam/splinter#718]
Hi, I posted this to Stackoverflow but not sure there's many people on there that know about Splinter, so I thought I'd post it here incase any of you have an idea :)

Here's the post: https://stackoverflow.com/questions/58106735/how-to-access-selenium-webdriver-through-splinter-in-python

Thanks for your time, really appreciate it.

**Comment by andrewsmedina** [comment]
The selenium webdriver is exposed by `driver` browser attribute:

```
>>> from splinter import Browser
b>>> b = Browser()
>>> b.driver
<selenium.webdriver.firefox.webdriver.WebDriver (session="e607ceaa-2c63-435e-9991-432376102bf5")>
>>> 
```

**Comment by JeffreyWinger55** [comment]
Thanks a ton Andrew - that's weird I tried that from memory and it didn't
work! I must have done something wrong. Will test it out later when I get
home. Thanks for your time.

**Comment by jsfehler** [comment]
Issue seems solved, so closing.
