### ISSUE TITLE
Chrome: screenshot_as_png() Not callable from browser or browser.driver 

### ISSUE THREAD

**Issue by gtamba** [cobrateam/splinter#751]
Hello, I was interested in being able to directly call [screenshot_as_png()](https://github.com/cobrateam/splinter/blob/9a79baf73f10d79e9b3d7695745c937154018874/splinter/driver/webdriver/__init__.py#L978) from the browser object instead of browser.screenshot which would require me to add an extra IO step in reading the image.

I'm using the Chrome Driver and getting the error 
```
AttributeError: 'WebDriver' object has no attribute 'screenshot_as_png'
```

But browser.screenshot('filename') seems to work fine, am I missing something? I even tried `browser.element_class.get_screenshot_as_png()` because I believe `.screenshot()` is dependent on `.screenshot_as_png()` if I'm not mistaken

**Comment by andrewsmedina** [comment]
The `screenshot_as_png` is an element method. So, you can select the `html` element and then call the `screenshot_as_png` method: `browser.find_by_tag('html'). screenshot_as_png()`

**Comment by gtamba** [comment]
Thank you for the clarification, I believe I blindly tried to mimic the api of other browser interfaces when I couldn't find the right codepath
