### ISSUE TITLE
Remote wedriver not working with arguments

### ISSUE THREAD

**Issue by mikiboy** [cobrateam/splinter#753]
As per the docs at https://splinter.readthedocs.io/en/latest/drivers/remote.html remote webdriver is supposed to work with `url` argument. But from the latest code for 0.13.0 it's changed completely.
My old code broke when building docker image with no version mentioned for the splinter in requirements file.
I checked the tests code [here](https://github.com/cobrateam/splinter/blob/master/tests/test_webdriver_remote.py) . Since there is no test with argument and abilities passed on it will go unnoticed.
Solution would be either updating the docs and tests for newer code or reverting to old argument names for remote web driver.

**Comment by jsfehler** [comment]
@andrewsmedina The files on readthedocs.io haven't been updated past 0.10.0

**Comment by andrewsmedina** [comment]
The sync between read the docs and github was broken. I have fixed it. So the 0.13.0 docs are online now.

**Comment by mikiboy** [comment]
Thanks guys for quick reply and doc fix.
