### ISSUE TITLE
Firefox does not open in fullscreen mode when passing the according keyword argument

### ISSUE THREAD

**Issue by dirkschneemann** [cobrateam/splinter#759]
The `fullscreen=True` argument to the Firefox browser constructor does not open the browser in full screen but in a regular non-maximized window instead:
```
from splinter import Browser

browser = Browser('firefox', fullscreen=True)
browser.visit('https://www.github.com')
```
Apart from that there is no error message.

For Chrome, however, it works just fine:
```
from splinter import Browser

browser = Browser('chrome', fullscreen=True)
browser.visit('https://www.github.com')
```

Versions:
* Ubuntu 18.04
* splinter 0.13.0
* selenium 3.141.0
* Firefox 73.0

**Comment by jsfehler** [comment]
Fixed by #765
