### ISSUE TITLE
UnboundLocalError when running splinter browser

### ISSUE THREAD

**Issue by EAly** [cobrateam/splinter#760]
I get this error:

~~~ 
UnboundLocalError: local variable 'e' referenced before assignment
~~~

When I try to use splinter browser as:

~~~
gekoExe_path = {'executable_path': <gekodriver path>}
browser= Browser('firefox', **gekoExe_path, headless= False)
~~~

I'm using splinter version: '0.13.0' and firefox

**Comment by mikiboy** [comment]
The Browser object has bug.
I see it fixed in the source code but not in the pip packages.

**Comment by EAly** [comment]
I solved that by installing the splinter from source code as mentioned [here](https://splinter.readthedocs.io/en/latest/install.html) and adding the gekodriver executable to path.

**Comment by mdilovar** [comment]
> The Browser object has bug.
> I see it fixed in the source code but not in the pip packages.

Are there any plans to create a new release? This bug is very frustrating as it prevents you from seeing the actual underlying exception.

**Comment by mikiboy** [comment]
Either you can use the source code directly in your project.
Or don't use the Browser object but directly call the required driver.

**Comment by petercoles** [comment]
Can't find anything in the documentation about how to use the source code directly or how to bypass the driver by calling the required driver directly. Wouldn't it be easier to simply release the corrected code?
