### ISSUE TITLE
Form submit action url is incorrectly derived in lxmldriver.py

### ISSUE THREAD

**Issue by olorton** [cobrateam/splinter#775]
If no action is set then the url is modified to append a slash which may not be a valid url. For example, the form on the following page `/question/95` would have an action set to `/question/95/` if no action is set. In my case I have resolved this issue by adding an action to my form.

If the maintainer could confirm that they would like a PR to fix this, then I will happily oblige.

**Comment by jsfehler** [comment]
@olorton We're always happy to get PRs for bug fixes. Thanks!

**Comment by jsfehler** [comment]
Fixed by #900
