### ISSUE TITLE
Bug in get_driver in 0.13.0

### ISSUE THREAD

**Issue by orokusaki** [cobrateam/splinter#778]
There is an extraneous `raise e` in [get_driver](https://github.com/cobrateam/splinter/blob/0.13.0/splinter/browser.py#L68) causing an `UnboundLocalError`.

**Comment by orokusaki** [comment]
I just realized that this bug has been fixed in `master`.

**Comment by isakson98** [comment]
how did you fix the problem?

**Comment by orokusaki** [comment]
@isakson98 the bug mentioned above is fixed in the master branch, but the underlying cause of the exception that led to me encountering the bug was just the need to update my chrome driver. The version I have installed supported Chrome 80, and apparently I recently updated to Chrome 83.

I’ll update Splinter when 0.14.0 comes out, but in the meantime here’s what I did:

    brew update
    brew upgrade chromedriver

**Comment by isakson98** [comment]
Thank you. I'll try it out. I have the exact same issue.
