### ISSUE TITLE
refactor form methods

### ISSUE THREAD

**Issue by andrewsmedina** [cobrateam/splinter#8]
splinter have finders by name, id, css_select, tag and xpath. But  check, fill_in, choose get elements by name:

```
browser.choose("some-radio")
```

It's need change this, moving these methods from browser class to element class:

```
checkbox = find_by_name('my-checkbox')
checkbox.check()
```

**Comment by jsfehler** [comment]
Closing, since #933 has deprecated the browser level functions. browser.find() uses name internally but this is configurable.
