### ISSUE TITLE
Is it possible to use flask driver AND chrome at the same time?

### ISSUE THREAD

**Issue by iandouglas** [cobrateam/splinter#813]
I really enjoy the flexibility of using both the Chrome driver and the Flask driver independently for various kinds of testing, but I'm curious if there's a way to have a test use both at the same time.

I'm trying to BDD my login with an OAuth provider (auth0.com), but I don't want to have to start running my app in another terminal window (plus I'm having a really hard time figuring out how to get travis-ci to play nicely with this).

```python
import pytest
from splinter import Browser
from run import app

with Browser('flask', app=app) as browser:
    browser.visit('/')
    browser.click_link_by_text('Login')
    # this passes
    assert 'auth0.com/authorize' in browser.url
    # this fails because clicking the Auth0 link is still trying to resolve the 
    # URL above within the Flask app context, so technically the page 
    # "loads" but it's the 404 page, so this form doesn't exist:
    browser.fill('username', authtest_username)
```

Could I somehow 'scrape' the login URL for Auth0 and have a second 'browser' object for chrome, visit the link in that browser, then get the resulting callback URL somehow and pass that back to the Flask browser?

Be neat if there was a way to blent this a little more seamlessly. I'd love any ideas others might have here.

**Comment by iandouglas** [comment]
The following seems to be a good start, but I'm curious if there's any better way to accomplish this?

```python
from splinter import Browser

from run import app

chrome = Browser('chrome', incognito=True)

with Browser('flask', app=app) as browser:
    # Visit URL
    browser.visit('/')
    # Find and click the 'search' button
    link = browser.find_link_by_partial_href('auth0.com/authorize')
    link = link.first.outer_html.split('"')[1].replace('&amp;', '&')
    chrome.visit(link)
```

**Comment by andrewsmedina** [comment]
Currently, the way to do it is like you have done, instantiating two browsers.
