### ISSUE TITLE
move from travis to github actions

### ISSUE THREAD

**Issue by andrewsmedina** [cobrateam/splinter#852]
travis-ci.org was scheduled for shutdown Dec 31, 2020. So, we should use github actions as CI.

**Comment by fsouza** [comment]
@andrewsmedina I can take care of that if you want or if you're not already working on it.

**Comment by jsfehler** [comment]
Fixed by #859

If there's any cleanup on travis-ci.org to do, I leave that to you.

**Comment by andrewsmedina** [comment]
@jsfehler very nice work! 👏
