### ISSUE TITLE
mouse actions long_click and right_long_click

### ISSUE THREAD

**Issue by thlengane** [cobrateam/splinter#861]
How can I lock_click on an object? I can do **double_click** and **right_click** without any problem but I would like to **long_click** or **right_long_click**. Is there anything I can do to achieve this?

**Comment by jsfehler** [comment]
There's currently no splinter method for this, but you can use ActionChains directly.

https://www.selenium.dev/selenium/docs/api/py/webdriver/selenium.webdriver.common.action_chains.html#selenium.webdriver.common.action_chains.ActionChains.click_and_hold

**Comment by jsfehler** [comment]
#

**Comment by thlengane** [comment]
@jsfehler I thought about that but the key_down/key_up methods take Keys, which is keyboard only if I am not mistaken. Is there a ways that I can send mouse keys on the key_down/key_up methods?

**Comment by jsfehler** [comment]
I really don't know what you mean. The `click_and_hold` method I linked you to is exactly that.
