### ISSUE TITLE
Support Shadow DOM or ShadowRoot

### ISSUE THREAD

**Issue by zodman** [cobrateam/splinter#876]
here some references:

https://stackoverflow.com/questions/37384458/how-to-handle-elements-inside-shadow-dom-from-selenium

```
def expand_shadow_element(element):
  shadow_root = driver.execute_script('return arguments[0].shadowRoot', element)
  return shadow_root

outer = expand_shadow_element(browser.find_by_css("#test_button"))
```

How convert outer to a ElementAPI ?

**Comment by jsfehler** [comment]
Shadow root support was added by #1025
