### ISSUE TITLE
Release 0.15.0?

### ISSUE THREAD

**Issue by turicas** [cobrateam/splinter#884]
Are there any plans to release version 0.15.0 (or 0.14.1)?
There are many useful commits since 0.14.0, including from this PR #810, which fixes a bug.

**Comment by andrewsmedina** [comment]
@turicas is right. We need to make a new release. I will make a release this week.

**Comment by flavianmissi** [comment]
@andrewsmedina is there anything you need to make it happen?

**Comment by andrewsmedina** [comment]
0.15.0 version released! https://github.com/cobrateam/splinter/releases/tag/0.15.0 - https://pypi.org/project/splinter/0.15.0/

**Comment by turicas** [comment]
Thanks!
