### ISSUE TITLE
Sample code in Splinter Documentation doesn't work

### ISSUE THREAD

**Issue by athulvis** [cobrateam/splinter#945]
It has been noticed that the sample code given in [Splinter Documentation](https://splinter.readthedocs.io/en/latest/) is not updated according to change in Google Search. Currently when we run the code, it throw outs the following error:
```
splinter.exceptions.ElementDoesNotExist: no elements could be found with name "btnG"
```
This is evident that Google modified the search button name from  `btnG`  to `btnK`. This is rectified in the `index` file in GitHub, but not in the documentation. It would be good if it is fixed in the documentation. Else it will be confusing to new users. 

Thanks anyway,

**Comment by jsfehler** [comment]
@andrewsmedina The relevant changes are merged in. If readthedocs is updated then this issue will be solved.

**Comment by deronnax** [comment]
Hello, what needs to be done for the readthedocs to be updated? it's been 4 months.

**Comment by fsouza** [comment]
Fixed the configuration for readthedocs. Sorry it took us so long.
