### ISSUE TITLE
Please release 0.17.0 to PyPI

### ISSUE THREAD

**Issue by return42** [cobrateam/splinter#969]
Can you please update splinter on [PyPi](https://pypi.org/project/splinter/) / thanks a lot!

@andrewsmedina @jsfehler

[1] https://github.com/cobrateam/splinter/pull/964#issuecomment-996604899

**Comment by jsfehler** [comment]
@andrewsmedina I've pushed the 0.17.0 release on github, all that's left is for you to build the wheel and push it to PyPi.

**Comment by andrewsmedina** [comment]
I will do it today

**Comment by andrewsmedina** [comment]
0.17.0 released! https://pypi.org/project/splinter/#history

**Comment by return42** [comment]
Cool / thanks a lot!
